import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts } from "pdf-lib";

export async function GET() {
  try {
    // Create new PDF
    const pdfDoc = await PDFDocument.create();

    // A4 landscape-ish page
    const page = pdfDoc.addPage([842, 595]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    /* ───────────────── HEADER ───────────────── */

    page.drawText("EduDecks Leadership Summary", {
      x: 40,
      y: height - 50,
      size: 22,
      font: bold,
    });

    page.drawText(
      "System report generated by EduDecks (safe build mode)",
      {
        x: 40,
        y: height - 75,
        size: 12,
        font,
      }
    );

    /* ───────────────── BODY ───────────────── */

    const lines = [
      "This PDF route is currently running without database integration.",
      "",
      "Next implementation step:",
      "• Connect Supabase server client",
      "• Pull leadership dashboard metrics",
      "• Render school / class analytics",
      "• Add export formatting",
      "",
      "Build is now unblocked.",
    ];

    let y = height - 120;

    for (const line of lines) {
      page.drawText(line, {
        x: 40,
        y,
        size: 12,
        font,
      });
      y -= 18;
    }

    /* ───────────────── FOOTER ───────────────── */

    page.drawText(`Generated: ${new Date().toLocaleString()}`, {
      x: 40,
      y: 30,
      size: 10,
      font,
    });

    /* ───────────────── SAVE ───────────────── */

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          'inline; filename="edudecks-leadership-summary.pdf"',
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("Leadership PDF route failed:", error);

    return NextResponse.json(
      { error: "Failed to generate leadership PDF" },
      { status: 500 }
    );
  }
}