import type { MyLearnaAssessmentItem } from "@/lib/clean/assessments/mylearnaAssessTypes";

export const MYLEARNA_ASSESS_DEMO_ITEMS: MyLearnaAssessmentItem[] = [
  {
    id: "npv-subitise-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Foundation",
      strand: "Number",
      substrand: "Number and Place Value",
    },
    skill: {
      id: "subitise-small-collections",
      name: "Recognise small collections without counting",
      description: "Identify a small quantity from a visual arrangement.",
    },
    misconceptionTags: ["counts-one-by-one", "confuses-scattered-arrangements"],
    difficulty: 1,
    template: "counter-card-choice",
    prompt: "Which number matches the counters?",
    stimulus: {
      type: "counter-set",
      data: {
        quantity: 4,
        arrangement: "scattered",
        seed: 1204,
      },
      altText: "Four counters shown in a scattered arrangement.",
    },
    response: {
      type: "single-choice",
      options: [
        {
          id: "a",
          label: "3",
          value: 3,
          feedback: "Count carefully. There are four counters.",
        },
        {
          id: "b",
          label: "4",
          value: 4,
          feedback: "Correct. There are four counters.",
        },
        {
          id: "c",
          label: "5",
          value: 5,
          feedback: "There are fewer than five counters.",
        },
      ],
      correctOptionIds: ["b"],
    },
    feedback: {
      correct: "Correct. You recognised the group of four.",
      incorrect: "Not quite. Look at the counters again and match the total.",
      hint: "Try touching each counter with your eyes as you count.",
    },
    analytics: {
      estimatedTimeSeconds: 30,
      tags: ["foundation", "number", "subitising", "counter-card-choice"],
    },
  },
  {
    id: "npv-subitise-002",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Foundation",
      strand: "Number",
      substrand: "Number and Place Value",
    },
    skill: {
      id: "subitise-small-collections",
      name: "Recognise small collections without counting",
      description: "Identify a small quantity from a visual arrangement.",
    },
    misconceptionTags: ["confuses-organised-arrangements"],
    difficulty: 1,
    template: "counter-card-choice",
    prompt: "How many counters are shown?",
    stimulus: {
      type: "counter-set",
      data: {
        quantity: 5,
        arrangement: "five-frame",
        seed: 1205,
      },
      altText: "Five counters shown in a clear five-frame arrangement.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "4", value: 4, feedback: "There is one more counter than four." },
        { id: "b", label: "6", value: 6, feedback: "There are fewer than six counters." },
        { id: "c", label: "5", value: 5, feedback: "Correct. The full row shows five." },
      ],
      correctOptionIds: ["c"],
    },
    feedback: {
      correct: "Correct. You recognised the full group of five.",
      incorrect: "Not quite. Look again at the full row of counters.",
      hint: "A full five-frame row has five spaces.",
    },
    analytics: {
      estimatedTimeSeconds: 25,
      tags: ["foundation", "number", "subitising", "five-frame"],
    },
  },
  {
    id: "npv-ten-frame-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Foundation",
      strand: "Number",
      substrand: "Number and Place Value",
    },
    skill: {
      id: "read-ten-frames",
      name: "Read quantities on a ten frame",
    },
    misconceptionTags: ["miscounts-empty-cells"],
    difficulty: 1,
    template: "ten-frame-choice",
    prompt: "How many spaces are filled?",
    stimulus: {
      type: "ten-frame",
      data: {
        filled: 7,
      },
      altText: "Ten frame showing 7 filled spaces out of 10.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "6", value: 6, feedback: "There is one more filled space than six." },
        { id: "b", label: "7", value: 7, feedback: "Correct. Seven spaces are filled." },
        { id: "c", label: "8", value: 8, feedback: "There is one fewer filled space than eight." },
        { id: "d", label: "10", value: 10, feedback: "Some spaces are still empty." },
      ],
      correctOptionIds: ["b"],
    },
    feedback: {
      correct: "Correct. Seven spaces are filled.",
      incorrect: "Not quite. Count the filled spaces before the empty spaces.",
      hint: "A full top row is five. Then count on.",
    },
    analytics: {
      estimatedTimeSeconds: 25,
      tags: ["foundation", "number", "ten-frame"],
    },
  },
  {
    id: "npv-number-line-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Year 1",
      strand: "Number",
      substrand: "Number and Place Value",
    },
    skill: {
      id: "read-number-lines",
      name: "Read a marked number line",
    },
    misconceptionTags: ["misreads-scale"],
    difficulty: 2,
    template: "number-line-choice",
    prompt: "Which number is marked on the number line?",
    stimulus: {
      type: "number-line",
      data: {
        min: 0,
        max: 10,
        step: 1,
        marker: 6,
        hiddenLabels: [6],
      },
      altText: "Number line from 0 to 10 with a marker at 6.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "5", value: 5, feedback: "The marker is one tick after five." },
        { id: "b", label: "6", value: 6, feedback: "Correct. The marker is at six." },
        { id: "c", label: "7", value: 7, feedback: "The marker is one tick before seven." },
        { id: "d", label: "10", value: 10, feedback: "The marker is not at the end of the line." },
      ],
      correctOptionIds: ["b"],
    },
    feedback: {
      correct: "Correct. The marker is at six.",
      incorrect: "Not quite. Follow the ticks from zero to the marker.",
      hint: "Count each tick by ones.",
    },
  },
  {
    id: "npv-array-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Year 2",
      strand: "Number",
      substrand: "Multiplication and Division",
    },
    skill: {
      id: "read-arrays",
      name: "Count equal rows and columns",
    },
    misconceptionTags: ["counts-only-one-row"],
    difficulty: 2,
    template: "array-choice",
    prompt: "How many items are in the array?",
    stimulus: {
      type: "array",
      data: {
        rows: 3,
        columns: 4,
        itemShape: "dot",
      },
      altText: "Array with 3 rows and 4 columns, showing 12 items.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "7", value: 7, feedback: "That adds the rows and columns, but the array shows all items." },
        { id: "b", label: "10", value: 10, feedback: "There are more than ten items." },
        { id: "c", label: "12", value: 12, feedback: "Correct. Three rows of four make twelve." },
        { id: "d", label: "14", value: 14, feedback: "There are fewer than fourteen items." },
      ],
      correctOptionIds: ["c"],
    },
    feedback: {
      correct: "Correct. Three rows of four make twelve.",
      incorrect: "Not quite. Count each row or skip count by fours.",
      hint: "There are 3 equal rows. Each row has 4.",
    },
  },
  {
    id: "npv-place-value-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Year 2",
      strand: "Number",
      substrand: "Number and Place Value",
    },
    skill: {
      id: "read-place-value-blocks",
      name: "Read hundreds, tens and ones",
    },
    misconceptionTags: ["ignores-zero-place", "confuses-tens-and-ones"],
    difficulty: 2,
    template: "place-value-blocks-choice",
    prompt: "What number is shown?",
    stimulus: {
      type: "place-value-blocks",
      data: {
        hundreds: 2,
        tens: 3,
        ones: 6,
      },
      altText: "Place-value blocks showing 2 hundreds, 3 tens, and 6 ones.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "236", value: 236, feedback: "Correct. 2 hundreds, 3 tens and 6 ones is 236." },
        { id: "b", label: "263", value: 263, feedback: "Check the tens and ones again." },
        { id: "c", label: "326", value: 326, feedback: "Check how many hundreds are shown." },
        { id: "d", label: "23", value: 23, feedback: "Do not forget the hundreds." },
      ],
      correctOptionIds: ["a"],
    },
    feedback: {
      correct: "Correct. The blocks show 236.",
      incorrect: "Not quite. Read hundreds first, then tens, then ones.",
      hint: "Hundreds are flats, tens are rods, ones are small cubes.",
    },
  },
  {
    id: "fdp-fraction-bar-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Year 3",
      strand: "Number",
      substrand: "Fractions",
    },
    skill: {
      id: "read-simple-fractions",
      name: "Read shaded parts of a whole",
    },
    misconceptionTags: ["counts-unshaded-parts", "confuses-numerator-denominator"],
    difficulty: 2,
    template: "fraction-bar-choice",
    prompt: "What fraction is shaded?",
    stimulus: {
      type: "fraction-bar",
      data: {
        numerator: 3,
        denominator: 4,
      },
      altText: "Fraction bar showing 3 out of 4 equal parts shaded.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "1/4", value: "1/4", feedback: "That is the unshaded part." },
        { id: "b", label: "3/4", value: "3/4", feedback: "Correct. Three of four equal parts are shaded." },
        { id: "c", label: "4/3", value: "4/3", feedback: "The total number of parts goes on the bottom." },
        { id: "d", label: "3/5", value: "3/5", feedback: "There are four equal parts, not five." },
      ],
      correctOptionIds: ["b"],
    },
    feedback: {
      correct: "Correct. Three quarters are shaded.",
      incorrect: "Not quite. Count shaded parts, then count total equal parts.",
      hint: "The top number is shaded parts. The bottom number is total parts.",
    },
  },
  {
    id: "geo-shape-set-001",
    version: 1,
    status: "draft",
    curriculum: {
      country: "Australia",
      jurisdiction: "ACARA",
      yearLevel: "Foundation",
      strand: "Geometry",
      substrand: "Shape",
    },
    skill: {
      id: "count-shapes-by-type",
      name: "Count shapes by type",
    },
    misconceptionTags: ["counts-all-shapes", "confuses-triangles-and-squares"],
    difficulty: 1,
    template: "shape-set-choice",
    prompt: "How many triangles are shown?",
    stimulus: {
      type: "shape-set",
      data: {
        arrangement: "scattered",
        seed: 321,
        shapes: [
          { type: "triangle", count: 3, size: "md" },
          { type: "circle", count: 2, size: "md" },
          { type: "square", count: 1, size: "md", rotation: 8 },
        ],
      },
      altText: "Set of shapes showing 3 triangles, 2 circles and 1 square.",
    },
    response: {
      type: "single-choice",
      options: [
        { id: "a", label: "2", value: 2, feedback: "That counts the circles." },
        { id: "b", label: "3", value: 3, feedback: "Correct. There are three triangles." },
        { id: "c", label: "5", value: 5, feedback: "That counts triangles and circles together." },
        { id: "d", label: "6", value: 6, feedback: "That counts all the shapes." },
      ],
      correctOptionIds: ["b"],
    },
    feedback: {
      correct: "Correct. There are three triangles.",
      incorrect: "Not quite. Count only the shapes with three sides.",
      hint: "A triangle has three sides.",
    },
  },
];
