import type {
  NumberAssessmentBankItem,
  NumberAssessmentBankKey,
} from "@/lib/clean/assessments/numberAssessmentBanks";
import { NUMBER_INTEGERS_COORDINATES_PROPERTIES_ITEM_BANK_KEY } from "@/lib/clean/assessments/numberIntegersCoordinatesPropertiesAssessmentItems";
import { NUMBER_PERCENT_RATIO_FINANCE_ITEM_BANK_KEY } from "@/lib/clean/assessments/numberPercentRatioFinanceAssessmentItems";
import { NUMBER_POWERS_ROOTS_ITEM_BANK_KEY } from "@/lib/clean/assessments/numberPowersRootsAssessmentItems";
import { NUMBER_RATIONAL_OPERATIONS_ITEM_BANK_KEY } from "@/lib/clean/assessments/numberRationalOperationsAssessmentItems";
import { NUMBER_SURDS_EXACT_ITEM_BANK_KEY } from "@/lib/clean/assessments/numberSurdsExactAssessmentItems";

export type Years910StepAssessmentDefinition = {
  key: string;
  stepNumber: number;
  stepKey: string;
  pathwayStepId: string;
  title: string;
  shortTitle: string;
  description: string;
  parentBankKey: NumberAssessmentBankKey;
  parentBankTitle: string;
  parentItemBankKey: string;
  progressionBandKey: string;
  items: NumberAssessmentBankItem[];
};

type ParentBank = {
  bankKey: NumberAssessmentBankKey;
  bankTitle: string;
  itemBankKey: string;
  progressionBandKey: string;
};

type Seed = {
  cluster: string;
  clusterTitle: string;
  title: string;
  prompt: string;
  options: string[];
  answer: string;
  visual: string;
  misconceptionTargets: string[];
};

const STAGE_KEY = "years-9-10-consolidation";
const APPROXIMATION_ITEM_BANK_KEY = "number-approximation-assessment-items-v1";

function slug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function pathwayStepId(stepKey: string) {
  return `mathematics::number-and-place-value::${STAGE_KEY}::${stepKey}`;
}

function visual(description: string) {
  return { type: "context_card" as const, description };
}

function makeItem(
  step: { number: number; key: string; description: string; progressionBandKey: string },
  seed: Seed,
  index: number,
): NumberAssessmentBankItem {
  return {
    id: `number-step-${step.number}-assess-${String(index + 1).padStart(3, "0")}`,
    progressionBandKey: step.progressionBandKey,
    progressionStepKey: step.key,
    subElementKey: seed.cluster,
    subElementTitle: seed.clusterTitle,
    subElementDescription: step.description,
    title: seed.title,
    prompt: seed.prompt,
    difficulty: index < 4 ? "foundation" : index < 8 ? "developing" : "secure",
    answerType: "multiple_choice",
    format: "years_9_10_visual_card",
    options: seed.options,
    expectedAnswer: seed.answer,
    acceptableAnswers: [seed.answer],
    markingGuide: "Auto-check the selected option.",
    workedSolution: seed.answer,
    misconceptionTargets: seed.misconceptionTargets,
    adaptiveRoute: {
      ifIncorrectGoToStepKey: step.key,
      ifCorrectGoToStepKey: step.key,
      practiceRecommendation: "Practise this exact pathway step with the matching visual model.",
      diagnosticNote: "This checks the learner's understanding for this pathway step.",
    },
    visualSupport: visual(seed.visual),
  };
}

function defineStep(
  stepNumber: number,
  title: string,
  shortTitle: string,
  description: string,
  parent: ParentBank,
  seeds: Seed[],
): Years910StepAssessmentDefinition {
  const stepKey = slug(title);
  return {
    key: `number-step-${stepNumber}-${stepKey}-assessment-v1`,
    stepNumber,
    stepKey,
    pathwayStepId: pathwayStepId(stepKey),
    title,
    shortTitle,
    description,
    parentBankKey: parent.bankKey,
    parentBankTitle: parent.bankTitle,
    parentItemBankKey: parent.itemBankKey,
    progressionBandKey: parent.progressionBandKey,
    items: seeds.map((seed, index) =>
      makeItem(
        { number: stepNumber, key: stepKey, description, progressionBandKey: parent.progressionBandKey },
        seed,
        index,
      ),
    ),
  };
}

const powersParent: ParentBank = {
  bankKey: "powers-roots-exponent-notation",
  bankTitle: "Powers and roots",
  itemBankKey: NUMBER_POWERS_ROOTS_ITEM_BANK_KEY,
  progressionBandKey: "powers-roots-exponent-notation",
};

const surdsParent: ParentBank = {
  bankKey: "surds-and-exact-form",
  bankTitle: "Surds and exact form",
  itemBankKey: NUMBER_SURDS_EXACT_ITEM_BANK_KEY,
  progressionBandKey: "surds-and-exact-form",
};

const percentParent: ParentBank = {
  bankKey: "percentages-ratio-financial-modelling",
  bankTitle: "Percent, ratio and finance",
  itemBankKey: NUMBER_PERCENT_RATIO_FINANCE_ITEM_BANK_KEY,
  progressionBandKey: "percentages-ratio-financial-modelling",
};

const integersParent: ParentBank = {
  bankKey: "integers-coordinates-number-properties",
  bankTitle: "Integers and coordinates",
  itemBankKey: NUMBER_INTEGERS_COORDINATES_PROPERTIES_ITEM_BANK_KEY,
  progressionBandKey: "integers-coordinates-number-properties",
};

const rationalParent: ParentBank = {
  bankKey: "rational-numbers-and-operations",
  bankTitle: "Rational operations",
  itemBankKey: NUMBER_RATIONAL_OPERATIONS_ITEM_BANK_KEY,
  progressionBandKey: "rational-numbers-and-operations",
};

const approximationParent: ParentBank = {
  bankKey: "approximation-estimation-error",
  bankTitle: "Approximation and error",
  itemBankKey: APPROXIMATION_ITEM_BANK_KEY,
  progressionBandKey: "approximation-estimation-error",
};

function standardFormSeeds(): Seed[] {
  return [
    {
      cluster: "large-scale-standard-form",
      clusterTitle: "Write large numbers",
      title: "Write 56,000 in standard form",
      prompt: "Write 56,000 in standard form.",
      options: ["5.6 x 10^4", "56 x 10^3", "0.56 x 10^5", "5.6 x 10^-4"],
      answer: "5.6 x 10^4",
      visual:
        "early-number|caption=Move the decimal so the first number is between 1 and 10.|numbers=56,000,5.6 x 10^4",
      misconceptionTargets: ["standard-form-leading-number-error", "positive-exponent-scale-gap"],
    },
    {
      cluster: "large-scale-standard-form",
      clusterTitle: "Write large numbers",
      title: "Write 7,800,000 in standard form",
      prompt: "Write 7,800,000 in standard form.",
      options: ["7.8 x 10^6", "78 x 10^5", "7.8 x 10^-6", "0.78 x 10^7"],
      answer: "7.8 x 10^6",
      visual:
        "early-number|caption=Large numbers use positive powers of 10.|numbers=7,800,000,7.8 x 10^6",
      misconceptionTargets: ["standard-form-leading-number-error", "positive-exponent-scale-gap"],
    },
    {
      cluster: "small-scale-standard-form",
      clusterTitle: "Write very small numbers",
      title: "Write 0.0045 in standard form",
      prompt: "Write 0.0045 in standard form.",
      options: ["4.5 x 10^-3", "4.5 x 10^3", "45 x 10^-4", "0.45 x 10^-2"],
      answer: "4.5 x 10^-3",
      visual:
        "early-number|caption=Very small numbers use negative powers of 10.|numbers=0.0045,4.5 x 10^-3",
      misconceptionTargets: ["negative-exponent-scale-gap", "standard-form-leading-number-error"],
    },
    {
      cluster: "small-scale-standard-form",
      clusterTitle: "Write very small numbers",
      title: "Write 0.000072 in standard form",
      prompt: "Write 0.000072 in standard form.",
      options: ["7.2 x 10^-5", "7.2 x 10^5", "72 x 10^-6", "0.72 x 10^-4"],
      answer: "7.2 x 10^-5",
      visual:
        "early-number|caption=Count the decimal-place shifts back to ordinary notation.|numbers=0.000072,7.2 x 10^-5",
      misconceptionTargets: ["negative-exponent-scale-gap", "standard-form-leading-number-error"],
    },
    {
      cluster: "convert-standard-form",
      clusterTitle: "Convert to ordinary notation",
      title: "Convert 2.4 x 10^3",
      prompt: "Write 2.4 x 10^3 as an ordinary number.",
      options: ["2,400", "240", "24,000", "0.0024"],
      answer: "2,400",
      visual:
        "early-number|caption=A positive exponent moves the decimal to make a larger number.|numbers=2.4 x 10^3,2,400",
      misconceptionTargets: ["positive-exponent-scale-gap", "place-value-shift-error"],
    },
    {
      cluster: "convert-standard-form",
      clusterTitle: "Convert to ordinary notation",
      title: "Convert 6.02 x 10^-4",
      prompt: "Write 6.02 x 10^-4 as an ordinary number.",
      options: ["0.000602", "0.00602", "6020", "0.0000602"],
      answer: "0.000602",
      visual:
        "early-number|caption=A negative exponent moves the decimal to make a smaller number.|numbers=6.02 x 10^-4,0.000602",
      misconceptionTargets: ["negative-exponent-scale-gap", "place-value-shift-error"],
    },
    {
      cluster: "compare-standard-form",
      clusterTitle: "Compare standard form",
      title: "Compare same powers",
      prompt: "Choose the correct symbol.",
      options: [">", "<", "="],
      answer: ">",
      visual:
        "early-number|caption=Compare the leading numbers when the powers of 10 match.|numbers=3.2 x 10^5,__,2.9 x 10^5",
      misconceptionTargets: ["standard-form-comparison-error", "leading-number-comparison-gap"],
    },
    {
      cluster: "compare-standard-form",
      clusterTitle: "Compare standard form",
      title: "Compare negative powers",
      prompt: "Choose the correct symbol.",
      options: ["<", ">", "="],
      answer: "<",
      visual:
        "early-number|caption=Convert or compare powers carefully when both numbers are small.|numbers=7.5 x 10^-3,__,2.1 x 10^-2",
      misconceptionTargets: ["negative-exponent-scale-gap", "standard-form-comparison-error"],
    },
    {
      cluster: "order-standard-form",
      clusterTitle: "Order standard form",
      title: "Order powers of 10",
      prompt: "Order these from least to greatest: 2.6 x 10^3, 2.6 x 10^5, 2.6 x 10^4, 2.6 x 10^2.",
      options: [
        "2.6 x 10^2, 2.6 x 10^3, 2.6 x 10^4, 2.6 x 10^5",
        "2.6 x 10^5, 2.6 x 10^4, 2.6 x 10^3, 2.6 x 10^2",
        "2.6 x 10^3, 2.6 x 10^2, 2.6 x 10^4, 2.6 x 10^5",
        "2.6 x 10^2, 2.6 x 10^4, 2.6 x 10^3, 2.6 x 10^5",
      ],
      answer: "2.6 x 10^2, 2.6 x 10^3, 2.6 x 10^4, 2.6 x 10^5",
      visual:
        "early-number|caption=The leading number is the same, so order the powers of 10.|numbers=2.6 x 10^2,2.6 x 10^3,2.6 x 10^4,2.6 x 10^5",
      misconceptionTargets: ["standard-form-ordering-error", "power-of-ten-order-gap"],
    },
    {
      cluster: "real-world-standard-form",
      clusterTitle: "Real-world standard form",
      title: "Earth to Sun distance",
      prompt: "The distance from Earth to the Sun is about 149,600,000 km. Write this number in standard form.",
      options: ["1.496 x 10^8 km", "14.96 x 10^7 km", "1.496 x 10^-8 km", "149.6 x 10^6 km"],
      answer: "1.496 x 10^8 km",
      visual:
        "early-number|caption=Standard form helps write very large real-world measurements compactly.|numbers=149,600,000 km,1.496 x 10^8 km",
      misconceptionTargets: ["real-world-scale-error", "standard-form-leading-number-error"],
    },
    {
      cluster: "real-world-standard-form",
      clusterTitle: "Real-world standard form",
      title: "Bacterium length",
      prompt: "A bacterium is about 0.0000025 m long. Write this number in standard form.",
      options: ["2.5 x 10^-6 m", "2.5 x 10^6 m", "25 x 10^-7 m", "0.25 x 10^-5 m"],
      answer: "2.5 x 10^-6 m",
      visual:
        "early-number|caption=Standard form helps write very small measurements compactly.|numbers=0.0000025 m,2.5 x 10^-6 m",
      misconceptionTargets: ["real-world-scale-error", "negative-exponent-scale-gap"],
    },
    {
      cluster: "calculate-standard-form",
      clusterTitle: "Calculate in standard form",
      title: "Multiply in standard form",
      prompt: "Calculate and give your answer in standard form.",
      options: ["1 x 10^6", "10 x 10^5", "1 x 10^5", "6.5 x 10^5"],
      answer: "1 x 10^6",
      visual:
        "early-number|caption=Multiply the leading numbers, add the powers of 10, then normalise.|numbers=(2.5 x 10^3) x (4 x 10^2),1 x 10^6",
      misconceptionTargets: ["standard-form-calculation-error", "normalise-standard-form-gap"],
    },
    {
      cluster: "calculate-standard-form",
      clusterTitle: "Calculate in standard form",
      title: "Divide in standard form",
      prompt: "Calculate and give your answer in standard form.",
      options: ["2.1 x 10^4", "2.1 x 10^3", "3.3 x 10^8", "18.9 x 10^4"],
      answer: "2.1 x 10^4",
      visual:
        "early-number|caption=Divide the leading numbers and subtract the powers of 10.|numbers=(6.3 x 10^6) / (3 x 10^2),2.1 x 10^4",
      misconceptionTargets: ["standard-form-calculation-error", "exponent-division-error"],
    },
    {
      cluster: "calculate-standard-form",
      clusterTitle: "Calculate in standard form",
      title: "Multiply small numbers",
      prompt: "Calculate and give your answer in standard form.",
      options: ["9 x 10^-7", "9 x 10^-1", "6.5 x 10^-7", "9 x 10^7"],
      answer: "9 x 10^-7",
      visual:
        "early-number|caption=Negative powers combine when multiplying very small numbers.|numbers=(4.5 x 10^-4) x (2 x 10^-3),9 x 10^-7",
      misconceptionTargets: ["negative-exponent-scale-gap", "standard-form-calculation-error"],
    },
    {
      cluster: "calculate-standard-form",
      clusterTitle: "Calculate in standard form",
      title: "Divide powers of ten",
      prompt: "Calculate and give your answer in standard form.",
      options: ["8 x 10^4", "8 x 10^12", "8 x 10^-4", "11.52 x 10^4"],
      answer: "8 x 10^4",
      visual:
        "early-number|caption=Divide 9.6 by 1.2, then subtract the exponents 8 - 4.|numbers=(9.6 x 10^8) / (1.2 x 10^4),8 x 10^4",
      misconceptionTargets: ["exponent-division-error", "standard-form-calculation-error"],
    },
  ];
}

function powersRootsSeeds(): Seed[] {
  const rows = [
    ["3^4", "81"], ["sqrt(144)", "12"], ["2^5 x 2^3", "2^8"], ["10^3", "1000"],
    ["sqrt(0.49)", "0.7"], ["5^0", "1"], ["9^(1/2)", "3"], ["4^3", "64"],
    ["sqrt(2.25)", "1.5"], ["7^2", "49"], ["2^-3", "1/8"], ["sqrt(196)", "14"],
  ];
  return rows.map(([question, answer], index) => ({
    cluster: index % 4 === 0 ? "powers" : index % 4 === 1 ? "roots" : index % 4 === 2 ? "index-laws" : "powers-in-context",
    clusterTitle: index % 4 === 0 ? "Powers" : index % 4 === 1 ? "Roots" : index % 4 === 2 ? "Index laws" : "Powers in context",
    title: question,
    prompt: `Which answer matches ${question}?`,
    options: [answer, "1", "12"],
    answer,
    visual: `early-number|caption=Connect the power or root to its value.|numbers=${question},${answer}`,
    misconceptionTargets: ["power-repeated-multiplication-gap", "root-inverse-gap"],
  }));
}

function exactFormSeeds(): Seed[] {
  return [
    {
      cluster: "exact-fraction-calculations",
      clusterTitle: "Exact fraction calculations",
      title: "Add fractions exactly",
      prompt: "Calculate and give your answer in simplest form.",
      options: ["5/6", "2/5", "1/5", "1"],
      answer: "5/6",
      visual:
        "early-number|caption=Use a common denominator and simplify the exact fraction.|numbers=1/2 + 1/3,5/6",
      misconceptionTargets: ["fraction-common-denominator-gap", "fraction-simplification-error"],
    },
    {
      cluster: "exact-fraction-calculations",
      clusterTitle: "Exact fraction calculations",
      title: "Subtract fractions exactly",
      prompt: "Calculate and give your answer in simplest form.",
      options: ["7/12", "2/10", "1/2", "5/12"],
      answer: "7/12",
      visual:
        "early-number|caption=Rewrite both fractions using twelfths, then subtract.|numbers=3/4 - 1/6,7/12",
      misconceptionTargets: ["fraction-common-denominator-gap", "fraction-subtraction-error"],
    },
    {
      cluster: "exact-fraction-calculations",
      clusterTitle: "Exact fraction calculations",
      title: "Multiply fractions exactly",
      prompt: "Calculate and give your answer in simplest form.",
      options: ["3/4", "30/13", "17/40", "1/4"],
      answer: "3/4",
      visual:
        "early-number|caption=Cancel common factors before or after multiplying.|numbers=2/5 x 15/8,3/4",
      misconceptionTargets: ["fraction-multiplication-error", "fraction-simplification-error"],
    },
    {
      cluster: "exact-fraction-calculations",
      clusterTitle: "Exact fraction calculations",
      title: "Divide fractions exactly",
      prompt: "Calculate and give your answer in simplest form.",
      options: ["3/2", "2/3", "21/14", "14/27"],
      answer: "3/2",
      visual:
        "early-number|caption=Divide by multiplying by the reciprocal, then simplify.|numbers=7/9 / 14/27,3/2",
      misconceptionTargets: ["fraction-division-reciprocal-gap", "fraction-simplification-error"],
    },
    {
      cluster: "fraction-contexts",
      clusterTitle: "Fractions in context",
      title: "Recipe fraction scale",
      prompt: "A recipe uses 2/3 cup of sugar. You want to make 1 1/2 times the recipe. How much sugar do you need?",
      options: ["1 cup", "2/3 cup", "3/2 cups", "4/3 cups"],
      answer: "1 cup",
      visual:
        "early-number|caption=Scale the recipe by multiplying the exact fractions.|numbers=2/3 x 3/2,1 cup",
      misconceptionTargets: ["fraction-context-operation-error", "mixed-number-conversion-gap"],
    },
    {
      cluster: "fraction-contexts",
      clusterTitle: "Fractions in context",
      title: "Tank fraction problem",
      prompt: "A tank is 3/5 full of water. Then 1/4 of the tank is added. What fraction of the tank is full now?",
      options: ["17/20", "4/9", "7/10", "1/5"],
      answer: "17/20",
      visual:
        "early-number|caption=Add the exact fractional parts using twentieths.|numbers=3/5 + 1/4,17/20",
      misconceptionTargets: ["fraction-context-operation-error", "fraction-common-denominator-gap"],
    },
    {
      cluster: "fraction-contexts",
      clusterTitle: "Fractions in context",
      title: "Rice fraction subtraction",
      prompt: "A bag has 5/8 kg of rice. You use 3/10 kg. How much rice is left?",
      options: ["13/40 kg", "2/18 kg", "1/4 kg", "7/20 kg"],
      answer: "13/40 kg",
      visual:
        "early-number|caption=Subtract exact amounts using fortieths.|numbers=5/8 - 3/10,13/40 kg",
      misconceptionTargets: ["fraction-context-operation-error", "fraction-subtraction-error"],
    },
    {
      cluster: "exact-pi-values",
      clusterTitle: "Exact pi expressions",
      title: "Combine multiples of pi",
      prompt: "Calculate exactly.",
      options: ["5pi", "6pi", "pi^5", "5"],
      answer: "5pi",
      visual:
        "early-number|caption=Combine like pi terms without changing pi to a decimal.|numbers=2pi + 3pi,5pi",
      misconceptionTargets: ["exact-form-rounded-too-early", "unlike-pi-term-error"],
    },
    {
      cluster: "exact-pi-values",
      clusterTitle: "Exact pi expressions",
      title: "Subtract multiples of pi",
      prompt: "Calculate exactly.",
      options: ["3pi", "11pi", "28pi", "3"],
      answer: "3pi",
      visual:
        "early-number|caption=Subtract the coefficients and keep pi exact.|numbers=7pi - 4pi,3pi",
      misconceptionTargets: ["exact-form-rounded-too-early", "unlike-pi-term-error"],
    },
    {
      cluster: "exact-pi-values",
      clusterTitle: "Exact pi expressions",
      title: "Add fractional multiples of pi",
      prompt: "Calculate exactly.",
      options: ["5pi/6", "2pi/5", "pi/6", "5/6"],
      answer: "5pi/6",
      visual:
        "early-number|caption=Use a common denominator for the coefficients, then keep pi exact.|numbers=pi/2 + pi/3,5pi/6",
      misconceptionTargets: ["fraction-common-denominator-gap", "exact-form-rounded-too-early"],
    },
    {
      cluster: "circle-exact-values",
      clusterTitle: "Circle exact values",
      title: "Circumference from radius",
      prompt: "Find the circumference of a circle with radius 7 cm. Give your answer in terms of pi.",
      options: ["14pi cm", "7pi cm", "49pi cm", "28pi cm"],
      answer: "14pi cm",
      visual:
        "early-number|caption=Use C = 2pi r and keep the answer exact.|numbers=r = 7 cm,C = 14pi cm",
      misconceptionTargets: ["radius-diameter-confusion", "circle-formula-error"],
    },
    {
      cluster: "circle-exact-values",
      clusterTitle: "Circle exact values",
      title: "Area from radius",
      prompt: "Find the area of a circle with radius 5 cm. Give your answer in terms of pi.",
      options: ["25pi cm^2", "10pi cm^2", "5pi cm^2", "20pi cm^2"],
      answer: "25pi cm^2",
      visual:
        "early-number|caption=Use A = pi r^2 and keep pi in the exact answer.|numbers=r = 5 cm,A = 25pi cm^2",
      misconceptionTargets: ["circle-formula-error", "square-radius-gap"],
    },
    {
      cluster: "circle-exact-values",
      clusterTitle: "Circle exact values",
      title: "Area from diameter",
      prompt: "Find the area of a circle with diameter 12 cm. Give your answer in terms of pi.",
      options: ["36pi cm^2", "12pi cm^2", "144pi cm^2", "24pi cm^2"],
      answer: "36pi cm^2",
      visual:
        "early-number|caption=Halve the diameter to get the radius before using A = pi r^2.|numbers=d = 12 cm,r = 6 cm,A = 36pi cm^2",
      misconceptionTargets: ["radius-diameter-confusion", "circle-formula-error"],
    },
    {
      cluster: "circle-exact-values",
      clusterTitle: "Circle exact values",
      title: "Radius from area",
      prompt: "A circular garden has area 36pi m^2. Find the radius of the garden.",
      options: ["6 m", "12 m", "36 m", "18 m"],
      answer: "6 m",
      visual:
        "early-number|caption=If A = pi r^2 and A = 36pi, then r^2 = 36.|numbers=A = 36pi m^2,r = 6 m",
      misconceptionTargets: ["inverse-circle-formula-gap", "square-root-gap"],
    },
    {
      cluster: "choose-exact-expression",
      clusterTitle: "Choose exact expressions",
      title: "Choose a fraction expression",
      prompt: "Three-quarters of 2/5 can be written as which expression?",
      options: ["3/4 x 2/5", "3/4 + 2/5", "3/4 / 2/5", "2/5 - 3/4"],
      answer: "3/4 x 2/5",
      visual:
        "early-number|caption=The word 'of' usually means multiply in fraction problems.|numbers=3/4 of 2/5,3/4 x 2/5",
      misconceptionTargets: ["fraction-context-operation-error", "expression-choice-error"],
    },
    {
      cluster: "choose-exact-expression",
      clusterTitle: "Choose exact expressions",
      title: "Twice a circumference",
      prompt: "Twice the circumference of a circle with radius r is:",
      options: ["2 x (2pi r)", "2pi r", "pi r^2", "2r"],
      answer: "2 x (2pi r)",
      visual:
        "early-number|caption=Start with the circumference formula, then multiply the whole expression by 2.|numbers=C = 2pi r,2 x (2pi r)",
      misconceptionTargets: ["circle-formula-error", "expression-choice-error"],
    },
    {
      cluster: "real-world-exact-values",
      clusterTitle: "Real-world exact answers",
      title: "Sector exact area",
      prompt: "A sector of a circle has radius 10 cm and central angle 60 degrees. What is the area of the sector?",
      options: ["50pi/3 cm^2", "100pi cm^2", "60pi cm^2", "10pi cm^2"],
      answer: "50pi/3 cm^2",
      visual:
        "early-number|caption=A 60 degree sector is 1/6 of the full circle area.|numbers=1/6 x 100pi,50pi/3 cm^2",
      misconceptionTargets: ["sector-fraction-gap", "circle-formula-error"],
    },
    {
      cluster: "real-world-exact-values",
      clusterTitle: "Real-world exact answers",
      title: "Wheel revolutions exact distance",
      prompt: "A wheel makes 15 complete revolutions. The wheel has radius 14 cm. How far does it travel?",
      options: ["420pi cm", "210pi cm", "28pi cm", "15pi cm"],
      answer: "420pi cm",
      visual:
        "early-number|caption=Distance is revolutions times circumference.|numbers=15 x 2pi x 14,420pi cm",
      misconceptionTargets: ["circle-context-operation-error", "radius-diameter-confusion"],
    },
    {
      cluster: "real-world-exact-values",
      clusterTitle: "Real-world exact answers",
      title: "Pizza exact area",
      prompt: "A pizza has a diameter of 30 cm. What is its area?",
      options: ["225pi cm^2", "30pi cm^2", "900pi cm^2", "15pi cm^2"],
      answer: "225pi cm^2",
      visual:
        "early-number|caption=Use radius 15 cm, then apply A = pi r^2.|numbers=d = 30 cm,r = 15 cm,A = 225pi cm^2",
      misconceptionTargets: ["radius-diameter-confusion", "circle-formula-error"],
    },
  ];
}

function percentageChangeSeeds(): Seed[] {
  return [
    {
      cluster: "percentage-increase",
      clusterTitle: "Percentage increase",
      title: "Increase 60 by 20%",
      prompt: "Increase 60 by 20%.",
      options: ["72", "80", "12", "48"],
      answer: "72",
      visual:
        "early-number|caption=20% of 60 is 12, so add it to the original value.|numbers=60 x 1.20,72",
      misconceptionTargets: ["percentage-change-base-error", "increase-decrease-direction-error"],
    },
    {
      cluster: "percentage-increase",
      clusterTitle: "Percentage increase",
      title: "Increase 150 by 35%",
      prompt: "Increase 150 by 35%.",
      options: ["202.5", "185", "52.5", "97.5"],
      answer: "202.5",
      visual:
        "early-number|caption=A 35% increase means multiply by 1.35.|numbers=150 x 1.35,202.5",
      misconceptionTargets: ["multiplier-method-gap", "percentage-change-base-error"],
    },
    {
      cluster: "percentage-increase",
      clusterTitle: "Percentage increase",
      title: "Increase money by 25%",
      prompt: "Increase £75 by 25%.",
      options: ["£93.75", "£100", "£18.75", "£56.25"],
      answer: "£93.75",
      visual:
        "early-number|caption=Use the increase multiplier 1.25 for a 25% increase.|numbers=£75 x 1.25,£93.75",
      misconceptionTargets: ["money-percentage-error", "multiplier-method-gap"],
    },
    {
      cluster: "percentage-decrease",
      clusterTitle: "Percentage decrease",
      title: "Decrease 80 by 20%",
      prompt: "Decrease 80 by 20%.",
      options: ["64", "60", "96", "16"],
      answer: "64",
      visual:
        "early-number|caption=A 20% decrease means multiply by 0.80.|numbers=80 x 0.80,64",
      misconceptionTargets: ["increase-decrease-direction-error", "multiplier-method-gap"],
    },
    {
      cluster: "percentage-decrease",
      clusterTitle: "Percentage decrease",
      title: "Decrease 200 by 15%",
      prompt: "Decrease 200 by 15%.",
      options: ["170", "185", "30", "215"],
      answer: "170",
      visual:
        "early-number|caption=A 15% decrease leaves 85%, so multiply by 0.85.|numbers=200 x 0.85,170",
      misconceptionTargets: ["increase-decrease-direction-error", "multiplier-method-gap"],
    },
    {
      cluster: "percentage-decrease",
      clusterTitle: "Percentage decrease",
      title: "Decrease money by 12%",
      prompt: "Decrease £500 by 12%.",
      options: ["£440", "£560", "£488", "£60"],
      answer: "£440",
      visual:
        "early-number|caption=A 12% decrease leaves 88% of the original amount.|numbers=£500 x 0.88,£440",
      misconceptionTargets: ["money-percentage-error", "increase-decrease-direction-error"],
    },
    {
      cluster: "multiplier-method",
      clusterTitle: "Percentage multipliers",
      title: "Choose increase multiplier",
      prompt: "Which multiplier represents a 25% increase?",
      options: ["1.25", "0.25", "0.75", "2.5"],
      answer: "1.25",
      visual:
        "early-number|caption=An increase multiplier is 1 plus the percentage as a decimal.|numbers=1 + 0.25,1.25",
      misconceptionTargets: ["multiplier-method-gap", "percentage-decimal-conversion-error"],
    },
    {
      cluster: "multiplier-method",
      clusterTitle: "Percentage multipliers",
      title: "Choose decrease multiplier",
      prompt: "Which multiplier represents a 30% decrease?",
      options: ["0.70", "1.30", "0.30", "1.70"],
      answer: "0.70",
      visual:
        "early-number|caption=A 30% decrease leaves 70% of the original value.|numbers=1 - 0.30,0.70",
      misconceptionTargets: ["multiplier-method-gap", "increase-decrease-direction-error"],
    },
    {
      cluster: "compound-growth",
      clusterTitle: "Compound growth",
      title: "Investment growth",
      prompt: "An investment of £1,000 grows by 5% each year. What is it worth after 3 years?",
      options: ["£1,157.63", "£1,150.00", "£1,050.00", "£1,215.51"],
      answer: "£1,157.63",
      visual:
        "early-number|caption=Compound growth repeats the multiplier each year.|numbers=1000 x 1.05^3,£1,157.63",
      misconceptionTargets: ["compound-growth-additive-error", "multiplier-method-gap"],
    },
    {
      cluster: "compound-growth",
      clusterTitle: "Compound growth",
      title: "Population growth",
      prompt: "A population of 2,000 increases by 3% each year. What is it after 4 years?",
      options: ["2,251", "2,240", "2,060", "2,600"],
      answer: "2,251",
      visual:
        "early-number|caption=Use the growth multiplier 1.03 four times, then round to a whole person.|numbers=2000 x 1.03^4,2,251",
      misconceptionTargets: ["compound-growth-additive-error", "rounding-context-gap"],
    },
    {
      cluster: "compound-decay",
      clusterTitle: "Compound decay",
      title: "Value decay",
      prompt: "A value of £5,000 decreases by 10% each year. What is it worth after 3 years?",
      options: ["£3,645", "£3,500", "£4,500", "£5,500"],
      answer: "£3,645",
      visual:
        "early-number|caption=Compound decay repeats the decrease multiplier each year.|numbers=5000 x 0.9^3,£3,645",
      misconceptionTargets: ["compound-decay-additive-error", "increase-decrease-direction-error"],
    },
    {
      cluster: "compound-decay",
      clusterTitle: "Compound decay",
      title: "Chemical decay",
      prompt: "A radioactive substance has a mass of 100 g and decays by 15% each year. What will be left after 2 years?",
      options: ["72.25 g", "70 g", "85 g", "115 g"],
      answer: "72.25 g",
      visual:
        "early-number|caption=A 15% decay leaves 85%, so use 0.85 twice.|numbers=100 x 0.85^2,72.25 g",
      misconceptionTargets: ["compound-decay-additive-error", "multiplier-method-gap"],
    },
    {
      cluster: "successive-percentage-change",
      clusterTitle: "Successive percentage changes",
      title: "Increase then decrease",
      prompt: "The price of a jacket is £80. It is increased by 15% and then decreased by 10%. What is the final price?",
      options: ["£82.80", "£84.00", "£92.00", "£72.00"],
      answer: "£82.80",
      visual:
        "early-number|caption=Successive changes multiply in sequence.|numbers=80 x 1.15 x 0.90,£82.80",
      misconceptionTargets: ["successive-percent-additive-error", "percentage-change-base-error"],
    },
    {
      cluster: "successive-percentage-change",
      clusterTitle: "Successive percentage changes",
      title: "Investment two-year growth",
      prompt: "An investment grows by 7% in the first year and by 5% in the second year. If the initial amount is £2,000, what is the value after 2 years?",
      options: ["£2,247", "£2,240", "£2,120", "£2,140"],
      answer: "£2,247",
      visual:
        "early-number|caption=Use each year's multiplier in order.|numbers=2000 x 1.07 x 1.05,£2,247",
      misconceptionTargets: ["successive-percent-additive-error", "money-percentage-error"],
    },
    {
      cluster: "successive-percentage-change",
      clusterTitle: "Successive percentage changes",
      title: "Depreciation over two years",
      prompt: "A laptop loses 25% of its value in the first year and 15% in the second year. If it originally cost £1,200, what is it worth after 2 years?",
      options: ["£765", "£720", "£900", "£1,020"],
      answer: "£765",
      visual:
        "early-number|caption=Depreciation uses decrease multipliers.|numbers=1200 x 0.75 x 0.85,£765",
      misconceptionTargets: ["successive-percent-additive-error", "compound-decay-additive-error"],
    },
    {
      cluster: "growth-decay-contexts",
      clusterTitle: "Growth and decay contexts",
      title: "Increase then same decrease",
      prompt: "A shop increases the price of a toy by 10%. A month later, it decreases the new price by 10%. What is true?",
      options: [
        "The final price is slightly less than the original price",
        "The final price is exactly the original price",
        "The final price is slightly more than the original price",
        "The final price is double the original price",
      ],
      answer: "The final price is slightly less than the original price",
      visual:
        "early-number|caption=The decrease is taken from the larger increased value, so the changes do not cancel.|numbers=original x 1.10 x 0.90,0.99 of original",
      misconceptionTargets: ["successive-percent-additive-error", "percentage-change-base-error"],
    },
    {
      cluster: "growth-decay-contexts",
      clusterTitle: "Growth and decay contexts",
      title: "Subscribers growth",
      prompt: "The number of subscribers to a channel increases by 12% each year. It currently has 15,000 subscribers. How many will it have after 3 years?",
      options: ["21,074", "20,000", "16,800", "18,600"],
      answer: "21,074",
      visual:
        "early-number|caption=Repeated growth uses the same multiplier each year.|numbers=15000 x 1.12^3,21,074",
      misconceptionTargets: ["compound-growth-additive-error", "rounding-context-gap"],
    },
    {
      cluster: "growth-decay-contexts",
      clusterTitle: "Growth and decay contexts",
      title: "Mixed yearly changes",
      prompt: "A value increases by 5% each year for 2 years and then decreases by 6% the following year. It was originally £300. What is its value now?",
      options: ["£310.91", "£315.00", "£297.00", "£330.75"],
      answer: "£310.91",
      visual:
        "early-number|caption=Apply each multiplier in sequence and round to the nearest penny.|numbers=300 x 1.05 x 1.05 x 0.94,£310.91",
      misconceptionTargets: ["successive-percent-additive-error", "money-percentage-error"],
    },
  ];
}

function ratioRateSeeds(): Seed[] {
  return [
    {
      cluster: "simplify-ratios",
      clusterTitle: "Simplify ratios",
      title: "Simplify 6 : 9",
      prompt: "Simplify the ratio.",
      options: ["2 : 3", "3 : 2", "6 : 3", "1 : 3"],
      answer: "2 : 3",
      visual: "early-number|caption=Divide both parts by the highest common factor.|numbers=6 : 9,2 : 3",
      misconceptionTargets: ["ratio-simplification-error", "common-factor-gap"],
    },
    {
      cluster: "simplify-ratios",
      clusterTitle: "Simplify ratios",
      title: "Simplify 15 : 25",
      prompt: "Simplify the ratio.",
      options: ["3 : 5", "5 : 3", "1 : 5", "15 : 5"],
      answer: "3 : 5",
      visual: "early-number|caption=Divide both parts by 5.|numbers=15 : 25,3 : 5",
      misconceptionTargets: ["ratio-simplification-error", "common-factor-gap"],
    },
    {
      cluster: "simplify-ratios",
      clusterTitle: "Simplify ratios",
      title: "Simplify 24 : 36 : 48",
      prompt: "Simplify the ratio.",
      options: ["2 : 3 : 4", "3 : 4 : 5", "4 : 6 : 8", "1 : 2 : 3"],
      answer: "2 : 3 : 4",
      visual: "early-number|caption=Divide all three parts by 12.|numbers=24 : 36 : 48,2 : 3 : 4",
      misconceptionTargets: ["three-part-ratio-gap", "common-factor-gap"],
    },
    {
      cluster: "ratio-sharing",
      clusterTitle: "Share in a ratio",
      title: "Share £60 in 2 : 3",
      prompt: "Share £60 in the ratio 2 : 3.",
      options: ["£24 and £36", "£20 and £40", "£30 and £30", "£12 and £48"],
      answer: "£24 and £36",
      visual: "early-number|caption=There are 5 parts. Each part is £12.|numbers=2 parts,3 parts,£24 and £36",
      misconceptionTargets: ["ratio-total-parts-error", "additive-ratio-error"],
    },
    {
      cluster: "ratio-sharing",
      clusterTitle: "Share in a ratio",
      title: "Share £120 in 2 : 3 : 5",
      prompt: "Share £120 in the ratio 2 : 3 : 5.",
      options: ["£24, £36 and £60", "£20, £30 and £70", "£30, £40 and £50", "£12, £36 and £72"],
      answer: "£24, £36 and £60",
      visual: "early-number|caption=There are 10 parts. Each part is £12.|numbers=2 : 3 : 5,£24, £36 and £60",
      misconceptionTargets: ["ratio-total-parts-error", "three-part-ratio-gap"],
    },
    {
      cluster: "direct-proportion",
      clusterTitle: "Direct proportion",
      title: "Direct proportion x = 4",
      prompt: "y is directly proportional to x. When x = 4, y = 18. Find y when x = 7.",
      options: ["31.5", "28", "25.2", "126"],
      answer: "31.5",
      visual: "early-number|caption=Find k first: k = 18 / 4 = 4.5.|numbers=y = kx,k = 4.5,y = 31.5",
      misconceptionTargets: ["direct-proportion-constant-error", "additive-ratio-error"],
    },
    {
      cluster: "direct-proportion",
      clusterTitle: "Direct proportion",
      title: "Direct proportion x = 6",
      prompt: "y is directly proportional to x. When x = 6, y = 24. Find y when x = 15.",
      options: ["60", "45", "90", "36"],
      answer: "60",
      visual: "early-number|caption=The constant is 4, so y = 4x.|numbers=y = 4x,x = 15,y = 60",
      misconceptionTargets: ["direct-proportion-constant-error", "scale-factor-gap"],
    },
    {
      cluster: "inverse-proportion",
      clusterTitle: "Inverse proportion",
      title: "Inverse proportion x = 4",
      prompt: "y is inversely proportional to x. When x = 4, y = 24. Find y when x = 6.",
      options: ["16", "36", "12", "144"],
      answer: "16",
      visual: "early-number|caption=For inverse proportion, xy stays constant.|numbers=xy = 96,x = 6,y = 16",
      misconceptionTargets: ["inverse-proportion-constant-error", "direct-inverse-confusion"],
    },
    {
      cluster: "inverse-proportion",
      clusterTitle: "Inverse proportion",
      title: "Inverse proportion x = 5",
      prompt: "y is inversely proportional to x. When x = 5, y = 30. Find y when x = 10.",
      options: ["15", "60", "20", "6"],
      answer: "15",
      visual: "early-number|caption=xy = 150, then divide by the new x.|numbers=xy = 150,x = 10,y = 15",
      misconceptionTargets: ["inverse-proportion-constant-error", "direct-inverse-confusion"],
    },
    {
      cluster: "fraction-proportions",
      clusterTitle: "Fraction proportions",
      title: "Solve 2/3 = x/12",
      prompt: "Solve the proportion.",
      options: ["8", "6", "18", "4"],
      answer: "8",
      visual: "early-number|caption=12 is 4 times 3, so x is 4 times 2.|numbers=2/3 = x/12,x = 8",
      misconceptionTargets: ["fraction-proportion-error", "cross-multiplication-gap"],
    },
    {
      cluster: "fraction-proportions",
      clusterTitle: "Fraction proportions",
      title: "Solve 4/7 = x/21",
      prompt: "Solve the proportion.",
      options: ["12", "14", "16", "10"],
      answer: "12",
      visual: "early-number|caption=21 is 3 times 7, so x = 4 times 3.|numbers=4/7 = x/21,x = 12",
      misconceptionTargets: ["fraction-proportion-error", "scale-factor-gap"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Car speed",
      prompt: "A car travels 240 km in 3 hours. What is the speed in km/h?",
      options: ["80 km/h", "720 km/h", "60 km/h", "243 km/h"],
      answer: "80 km/h",
      visual: "early-number|caption=Speed = distance / time.|numbers=240 km / 3 h,80 km/h",
      misconceptionTargets: ["unit-rate-gap", "speed-distance-time-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Water flow rate",
      prompt: "A tank is filled with 300 litres of water in 6 minutes. How many litres are added in 10 minutes?",
      options: ["500 litres", "50 litres", "300 litres", "600 litres"],
      answer: "500 litres",
      visual: "early-number|caption=Find litres per minute, then multiply by 10.|numbers=300 / 6 = 50 L/min,500 litres",
      misconceptionTargets: ["unit-rate-gap", "rate-time-scaling-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Cyclist speed",
      prompt: "A cyclist travels 90 km in 2.5 hours. What is the average speed?",
      options: ["36 km/h", "45 km/h", "90 km/h", "225 km/h"],
      answer: "36 km/h",
      visual: "early-number|caption=Average speed is total distance divided by total time.|numbers=90 / 2.5,36 km/h",
      misconceptionTargets: ["decimal-rate-error", "speed-distance-time-error"],
    },
    {
      cluster: "scale-and-proportion",
      clusterTitle: "Scale and proportion",
      title: "Recipe scaling",
      prompt: "A recipe uses 120 g of sugar for 8 cakes. How much sugar is needed for 15 cakes?",
      options: ["225 g", "180 g", "240 g", "160 g"],
      answer: "225 g",
      visual: "early-number|caption=Find sugar per cake, then scale to 15 cakes.|numbers=120 / 8 = 15 g,15 x 15 = 225 g",
      misconceptionTargets: ["unit-rate-gap", "recipe-scaling-error"],
    },
    {
      cluster: "scale-and-proportion",
      clusterTitle: "Scale and proportion",
      title: "Map scale",
      prompt: "A map scale is 1 cm : 5 km. If the distance is 15 cm on the map, what is the actual distance?",
      options: ["75 km", "20 km", "3 km", "50 km"],
      answer: "75 km",
      visual: "early-number|caption=Each map centimetre represents 5 kilometres.|numbers=15 x 5,75 km",
      misconceptionTargets: ["scale-factor-gap", "map-scale-error"],
    },
    {
      cluster: "inverse-proportion",
      clusterTitle: "Inverse proportion",
      title: "Workers and time",
      prompt: "It takes 6 workers 10 days to complete a job. How long will 4 workers take?",
      options: ["15 days", "12 days", "8 days", "20 days"],
      answer: "15 days",
      visual: "early-number|caption=Worker-days stay constant when workers and time are inverse.|numbers=6 x 10 = 60 worker-days,60 / 4 = 15 days",
      misconceptionTargets: ["worker-time-inverse-error", "direct-inverse-confusion"],
    },
    {
      cluster: "growth-rate-contexts",
      clusterTitle: "Real-world rate contexts",
      title: "Bacteria doubling",
      prompt: "A population of bacteria doubles every 3 hours. If the initial population is 500, what is it after 12 hours?",
      options: ["8,000", "2,000", "4,000", "6,000"],
      answer: "8,000",
      visual: "early-number|caption=12 hours is 4 doubling periods.|numbers=500 x 2^4,8,000",
      misconceptionTargets: ["rate-period-error", "exponential-context-gap"],
    },
  ];
}

function algebraGraphSeeds(): Seed[] {
  return [
    {
      cluster: "simplify-expressions",
      clusterTitle: "Simplify expressions",
      title: "Simplify like terms",
      prompt: "Simplify the expression.",
      options: ["0", "14x", "7x", "-7x"],
      answer: "0",
      visual: "early-number|caption=Collect like terms carefully.|numbers=3x + 4x - 7x,0",
      misconceptionTargets: ["like-terms-error", "integer-operation-error"],
    },
    {
      cluster: "simplify-expressions",
      clusterTitle: "Simplify expressions",
      title: "Simplify a expression",
      prompt: "Simplify the expression.",
      options: ["6a", "4a", "10a", "5a"],
      answer: "6a",
      visual: "early-number|caption=Collect the a terms only.|numbers=5a - 2a + 3a,6a",
      misconceptionTargets: ["like-terms-error", "coefficient-combination-error"],
    },
    {
      cluster: "simplify-expressions",
      clusterTitle: "Simplify expressions",
      title: "Simplify variables and numbers",
      prompt: "Simplify the expression.",
      options: ["4y + 5", "8y + 5", "4y + 11", "8y - 5"],
      answer: "4y + 5",
      visual: "early-number|caption=Collect variable terms and number terms separately.|numbers=6y + 8 - 2y - 3,4y + 5",
      misconceptionTargets: ["like-terms-error", "constant-term-error"],
    },
    {
      cluster: "expand-and-simplify",
      clusterTitle: "Expand and simplify",
      title: "Expand and simplify brackets",
      prompt: "Simplify the expression.",
      options: ["4b - 6", "4b + 6", "10b + 6", "7b - 3b + 2"],
      answer: "4b - 6",
      visual: "early-number|caption=Expand the bracket, then collect like terms.|numbers=7b - 3(b + 2),4b - 6",
      misconceptionTargets: ["distributive-law-error", "negative-bracket-error"],
    },
    {
      cluster: "expand-and-simplify",
      clusterTitle: "Expand and simplify",
      title: "Expand x brackets",
      prompt: "Simplify the expression.",
      options: ["10 - x", "5x + 10", "-x + 5", "2x + 5"],
      answer: "10 - x",
      visual: "early-number|caption=Expand 2(x + 5), then subtract 3x.|numbers=2(x + 5) - 3x,10 - x",
      misconceptionTargets: ["distributive-law-error", "like-terms-error"],
    },
    {
      cluster: "solve-linear-equations",
      clusterTitle: "Solve equations",
      title: "Solve 3x + 5 = 20",
      prompt: "Solve the equation.",
      options: ["x = 5", "x = 15", "x = 25", "x = 3"],
      answer: "x = 5",
      visual: "early-number|caption=Use inverse operations and keep both sides balanced.|numbers=3x + 5 = 20,x = 5",
      misconceptionTargets: ["inverse-operation-gap", "equation-balance-error"],
    },
    {
      cluster: "solve-linear-equations",
      clusterTitle: "Solve equations",
      title: "Solve 2x - 7 = 11",
      prompt: "Solve the equation.",
      options: ["x = 9", "x = 2", "x = 18", "x = 4"],
      answer: "x = 9",
      visual: "early-number|caption=Add 7, then divide by 2.|numbers=2x - 7 = 11,x = 9",
      misconceptionTargets: ["inverse-operation-gap", "equation-balance-error"],
    },
    {
      cluster: "solve-linear-equations",
      clusterTitle: "Solve equations",
      title: "Solve with brackets",
      prompt: "Solve the equation.",
      options: ["x = 7", "x = 12", "x = 2", "x = 14"],
      answer: "x = 7",
      visual: "early-number|caption=Divide by 2 first, then undo the +5.|numbers=2(x + 5) = 24,x = 7",
      misconceptionTargets: ["bracket-equation-error", "inverse-operation-gap"],
    },
    {
      cluster: "solve-linear-equations",
      clusterTitle: "Solve equations",
      title: "Variables on both sides",
      prompt: "Solve the equation.",
      options: ["x = 4", "x = -4", "x = 2", "x = 8"],
      answer: "x = 4",
      visual: "early-number|caption=Move variable terms to one side and constants to the other.|numbers=3x + 2 = 5x - 6,x = 4",
      misconceptionTargets: ["variables-both-sides-error", "equation-balance-error"],
    },
    {
      cluster: "substitution",
      clusterTitle: "Substitution",
      title: "Substitute x = 5",
      prompt: "Find the value of the expression when x = 5.",
      options: ["13", "10", "8", "15"],
      answer: "13",
      visual: "early-number|caption=Replace x with 5, then follow order of operations.|numbers=2x + 3,13",
      misconceptionTargets: ["substitution-order-error", "variable-value-gap"],
    },
    {
      cluster: "substitution",
      clusterTitle: "Substitution",
      title: "Substitute negative value",
      prompt: "Find the value of the expression when a = -2.",
      options: ["-10", "2", "10", "-2"],
      answer: "-10",
      visual: "early-number|caption=Keep the negative sign with the substituted value.|numbers=3a - 4,-10",
      misconceptionTargets: ["negative-substitution-error", "integer-operation-error"],
    },
    {
      cluster: "substitution",
      clusterTitle: "Substitution",
      title: "Substitute with powers",
      prompt: "Find the value of the expression when b = 3.",
      options: ["33", "9", "21", "36"],
      answer: "33",
      visual: "early-number|caption=Square first, then multiply and subtract.|numbers=4b^2 - b,33",
      misconceptionTargets: ["order-of-operations-error", "power-substitution-error"],
    },
    {
      cluster: "substitution",
      clusterTitle: "Substitution",
      title: "Substitute negative with powers",
      prompt: "Find the value of the expression when x = -3.",
      options: ["2", "-16", "14", "-4"],
      answer: "2",
      visual: "early-number|caption=(-3)^2 is positive before adding 2(-3) and subtracting 1.|numbers=x^2 + 2x - 1,2",
      misconceptionTargets: ["negative-square-error", "order-of-operations-error"],
    },
    {
      cluster: "gradient-and-intercept",
      clusterTitle: "Gradient and intercept",
      title: "Gradient from rise and run",
      prompt: "A straight line rises 3 units for every 2 units it moves right. What is its gradient?",
      options: ["3/2", "2/3", "3", "2"],
      answer: "3/2",
      visual: "early-number|caption=Gradient is rise divided by run.|numbers=rise 3,run 2,gradient 3/2",
      misconceptionTargets: ["gradient-rise-run-error", "coordinate-rate-gap"],
    },
    {
      cluster: "gradient-and-intercept",
      clusterTitle: "Gradient and intercept",
      title: "Find y-intercept",
      prompt: "A straight line crosses the y-axis at 4. What is the y-intercept?",
      options: ["4", "-4", "0", "1"],
      answer: "4",
      visual: "early-number|caption=The y-intercept is where the line crosses the y-axis.|numbers=y-axis,4",
      misconceptionTargets: ["intercept-axis-error", "coordinate-reading-error"],
    },
    {
      cluster: "line-equations",
      clusterTitle: "Line equations",
      title: "Equation of a line",
      prompt: "A line has gradient 2 and y-intercept -3. What is its equation?",
      options: ["y = 2x - 3", "y = -3x + 2", "y = 2x + 3", "y = x - 3"],
      answer: "y = 2x - 3",
      visual: "early-number|caption=Use y = mx + c with m = 2 and c = -3.|numbers=m = 2,c = -3,y = 2x - 3",
      misconceptionTargets: ["line-equation-form-error", "gradient-intercept-swap"],
    },
    {
      cluster: "graph-interpretation",
      clusterTitle: "Graph interpretation",
      title: "Distance-time graph",
      prompt: "A car travels 160 km in 4 hours at a constant speed. What is the distance after 2.5 hours?",
      options: ["100 km", "80 km", "120 km", "64 km"],
      answer: "100 km",
      visual: "early-number|caption=Find the constant speed first, then multiply by time.|numbers=160 / 4 = 40 km/h,40 x 2.5 = 100 km",
      misconceptionTargets: ["graph-rate-error", "speed-distance-time-error"],
    },
    {
      cluster: "algebraic-word-problems",
      clusterTitle: "Algebraic word problems",
      title: "Write equation from words",
      prompt: "The sum of three times a number and 7 is 22. Which equation represents the problem?",
      options: ["3x + 7 = 22", "3x - 7 = 22", "x + 7 = 3", "7x + 3 = 22"],
      answer: "3x + 7 = 22",
      visual: "early-number|caption=Translate the words into an equation before solving.|numbers=three times a number + 7,3x + 7 = 22",
      misconceptionTargets: ["word-problem-equation-error", "operation-language-gap"],
    },
    {
      cluster: "algebraic-word-problems",
      clusterTitle: "Algebraic word problems",
      title: "Solve word problem",
      prompt: "The sum of three times a number and 7 is 22. What is the number?",
      options: ["5", "15", "29", "3"],
      answer: "5",
      visual: "early-number|caption=Solve 3x + 7 = 22 using inverse operations.|numbers=3x + 7 = 22,x = 5",
      misconceptionTargets: ["word-problem-equation-error", "equation-balance-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Average speed",
      prompt: "A car travels 180 km in 3 hours. What is the average speed?",
      options: ["60 km/h", "540 km/h", "180 km/h", "3 km/h"],
      answer: "60 km/h",
      visual: "early-number|caption=Rate of change is change in amount divided by change in time.|numbers=180 / 3,60 km/h",
      misconceptionTargets: ["rate-of-change-error", "speed-distance-time-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Bacteria rate of change",
      prompt: "The number of bacteria increases from 500 to 2,000 in 6 hours. What is the average increase per hour?",
      options: ["250 bacteria per hour", "333 bacteria per hour", "1,500 bacteria per hour", "6 bacteria per hour"],
      answer: "250 bacteria per hour",
      visual: "early-number|caption=Find the change, then divide by the time.|numbers=2000 - 500 = 1500,1500 / 6 = 250 per hour",
      misconceptionTargets: ["rate-of-change-error", "difference-vs-final-value-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Savings rate of change",
      prompt: "A savings account increases from £250 to £1,950 in 5 months. What is the rate of increase per month?",
      options: ["£340 per month", "£390 per month", "£250 per month", "£1,700 per month"],
      answer: "£340 per month",
      visual: "early-number|caption=The increase is £1,700, then divide by 5 months.|numbers=1950 - 250 = 1700,1700 / 5 = £340/month",
      misconceptionTargets: ["rate-of-change-error", "money-context-error"],
    },
    {
      cluster: "rates-of-change",
      clusterTitle: "Rates of change",
      title: "Depreciation rate",
      prompt: "The price of a laptop decreases from £600 to £450 in 10 months. What is the rate of decrease per month?",
      options: ["£15 per month", "£45 per month", "£150 per month", "£10 per month"],
      answer: "£15 per month",
      visual: "early-number|caption=The decrease is £150, then divide by 10 months.|numbers=600 - 450 = 150,150 / 10 = £15/month",
      misconceptionTargets: ["rate-of-change-error", "decrease-direction-error"],
    },
  ];
}

function financialModellingSeeds(): Seed[] {
  return [
    {
      cluster: "budgeting-and-money",
      clusterTitle: "Budgeting and money",
      title: "Amira budget",
      prompt: "Amira has £42.75. She spends £18.60 on books and £7.45 on lunch. How much money does she save?",
      options: ["£16.70", "£24.15", "£17.70", "£25.15"],
      answer: "£16.70",
      visual: "early-number|caption=Subtract each cost from the starting amount.|numbers=£42.75 - £18.60 - £7.45,£16.70",
      misconceptionTargets: ["budgeting-subtraction-error", "money-place-value-error"],
    },
    {
      cluster: "budgeting-and-money",
      clusterTitle: "Budgeting and money",
      title: "Family weekly budget",
      prompt: "A family has a weekly budget of £350 for food, transport and entertainment. They spend £142.80 on food and £68.65 on transport. How much is left for entertainment?",
      options: ["£138.55", "£139.55", "£281.35", "£118.55"],
      answer: "£138.55",
      visual: "early-number|caption=Subtract food and transport from the total budget.|numbers=£350 - £142.80 - £68.65,£138.55",
      misconceptionTargets: ["budgeting-subtraction-error", "multi-step-money-error"],
    },
    {
      cluster: "percentages-and-discounts",
      clusterTitle: "Percentages and discounts",
      title: "Jacket sale price",
      prompt: "A jacket costs £75. It is on sale for 20% off. What is the sale price?",
      options: ["£60", "£55", "£15", "£95"],
      answer: "£60",
      visual: "early-number|caption=Find the discount, then subtract it from the original price.|numbers=20% of £75 = £15,£75 - £15 = £60",
      misconceptionTargets: ["discount-vs-saving-error", "percentage-money-gap"],
    },
    {
      cluster: "budgeting-and-money",
      clusterTitle: "Budgeting and money",
      title: "Shopping change",
      prompt: "Mia buys jeans for £28.00 and a top for £17.50. She pays with a £50 note. How much change does she get?",
      options: ["£4.50", "£5.50", "£45.50", "£3.50"],
      answer: "£4.50",
      visual: "early-number|caption=Add the spending, then subtract from the amount paid.|numbers=£28.00 + £17.50 = £45.50,£50 - £45.50 = £4.50",
      misconceptionTargets: ["change-calculation-error", "money-place-value-error"],
    },
    {
      cluster: "best-buys-unit-price",
      clusterTitle: "Best buys and unit price",
      title: "Cereal best buy",
      prompt: "Pack A has 500 g of cereal for £1.65. Pack B has 750 g of cereal for £2.25. Which is the better value?",
      options: ["Pack B", "Pack A", "They are equal value", "Cannot tell"],
      answer: "Pack B",
      visual: "early-number|caption=Compare price per gram for the same unit.|numbers=£1.65 / 500 g,£2.25 / 750 g,Pack B",
      misconceptionTargets: ["unit-price-error", "best-buy-size-error"],
    },
    {
      cluster: "best-buys-unit-price",
      clusterTitle: "Best buys and unit price",
      title: "Rolls best value",
      prompt: "Store X sells 12 rolls of toilet paper for £5.40. Store Y sells 18 rolls of toilet paper for £7.20. Which store is better value?",
      options: ["Store Y", "Store X", "They are equal value", "Cannot tell"],
      answer: "Store Y",
      visual: "early-number|caption=Find the cost per roll before comparing.|numbers=£5.40 / 12 = 45p,£7.20 / 18 = 40p,Store Y",
      misconceptionTargets: ["unit-price-error", "lower-total-price-error"],
    },
    {
      cluster: "best-buys-unit-price",
      clusterTitle: "Best buys and unit price",
      title: "Juice best value",
      prompt: "Pack M has 250 ml of juice for 85p. Pack N has 400 ml of juice for £1.20. Which pack is better value?",
      options: ["Pack N", "Pack M", "They are equal value", "Cannot tell"],
      answer: "Pack N",
      visual: "early-number|caption=Compare cost per millilitre.|numbers=85p / 250 ml,£1.20 / 400 ml,Pack N",
      misconceptionTargets: ["unit-price-error", "mixed-units-error"],
    },
    {
      cluster: "best-buys-unit-price",
      clusterTitle: "Best buys and unit price",
      title: "Apple bag best value",
      prompt: "Bag P has 1.5 kg of apples for £2.10. Bag Q has 2 kg of apples for £2.70. Which bag is better value?",
      options: ["Bag Q", "Bag P", "They are equal value", "Cannot tell"],
      answer: "Bag Q",
      visual: "early-number|caption=Compare cost per kilogram.|numbers=£2.10 / 1.5 kg = £1.40/kg,£2.70 / 2 kg = £1.35/kg,Bag Q",
      misconceptionTargets: ["unit-price-error", "decimal-division-error"],
    },
    {
      cluster: "time-and-work",
      clusterTitle: "Time and work",
      title: "Train journey time",
      prompt: "A train leaves London at 09:45 and arrives in Manchester at 13:30. How long is the journey?",
      options: ["3 hours 45 minutes", "4 hours 15 minutes", "3 hours 30 minutes", "4 hours 45 minutes"],
      answer: "3 hours 45 minutes",
      visual: "early-number|caption=Count from the start time to the arrival time.|numbers=09:45 to 13:30,3 hours 45 minutes",
      misconceptionTargets: ["time-interval-error", "clock-crossing-hour-error"],
    },
    {
      cluster: "time-and-work",
      clusterTitle: "Time and work",
      title: "Machine production rate",
      prompt: "A machine makes 360 widgets in 6 hours. How many widgets can it make in 8 hours?",
      options: ["480", "420", "60", "540"],
      answer: "480",
      visual: "early-number|caption=Find the hourly rate, then multiply by the new time.|numbers=360 / 6 = 60 per hour,60 x 8 = 480",
      misconceptionTargets: ["rate-error", "multiplicative-scaling-error"],
    },
    {
      cluster: "time-and-work",
      clusterTitle: "Time and work",
      title: "Workers and time",
      prompt: "8 workers can paint a fence in 9 days. If they work at the same rate, how long will 6 workers take?",
      options: ["12 days", "10 days", "15 days", "6 days"],
      answer: "12 days",
      visual: "early-number|caption=Worker-days stay constant when the rate is the same.|numbers=8 x 9 = 72 worker-days,72 / 6 = 12 days",
      misconceptionTargets: ["inverse-proportion-error", "worker-time-error"],
    },
    {
      cluster: "measurement-and-units",
      clusterTitle: "Measurement and units",
      title: "Milk conversion",
      prompt: "A recipe needs 17.5 L of milk. How many millilitres is this?",
      options: ["17,500 ml", "1,750 ml", "175 ml", "175,000 ml"],
      answer: "17,500 ml",
      visual: "early-number|caption=Convert litres to millilitres by multiplying by 1000.|numbers=17.5 L x 1000,17,500 ml",
      misconceptionTargets: ["unit-conversion-error", "place-value-scaling-error"],
    },
    {
      cluster: "measurement-and-units",
      clusterTitle: "Measurement and units",
      title: "Carpet area and cost",
      prompt: "A room is 5.4 m long and 3.8 m wide. Carpet costs £18.50 per square metre. What is the carpet cost?",
      options: ["£379.62", "£170.20", "£20.52", "£999.00"],
      answer: "£379.62",
      visual: "early-number|caption=Find the area, then multiply by cost per square metre.|numbers=5.4 x 3.8 = 20.52 m^2,20.52 x £18.50 = £379.62",
      misconceptionTargets: ["area-cost-error", "multi-step-measurement-error"],
    },
    {
      cluster: "measurement-and-units",
      clusterTitle: "Measurement and units",
      title: "Average apple mass",
      prompt: "A box has a mass of 2.6 kg and contains 8 apples. What is the average mass of one apple?",
      options: ["0.325 kg", "0.26 kg", "3.25 kg", "20.8 kg"],
      answer: "0.325 kg",
      visual: "early-number|caption=Average mass is total mass divided by the number of items.|numbers=2.6 / 8,0.325 kg",
      misconceptionTargets: ["average-division-error", "decimal-division-error"],
    },
    {
      cluster: "measurement-and-units",
      clusterTitle: "Measurement and units",
      title: "Tank capacity",
      prompt: "A tank holds 1,800 L of water. It is filled to 65% of its capacity. How many litres of water are in the tank?",
      options: ["1,170 L", "650 L", "1,800 L", "1,350 L"],
      answer: "1,170 L",
      visual: "early-number|caption=Find 65% of the total capacity.|numbers=0.65 x 1800,1,170 L",
      misconceptionTargets: ["percentage-of-amount-error", "capacity-context-error"],
    },
    {
      cluster: "percentages-and-discounts",
      clusterTitle: "Percentages and discounts",
      title: "Television percentage decrease",
      prompt: "A television is reduced from £420 to £336. What is the percentage decrease?",
      options: ["20%", "25%", "84%", "15%"],
      answer: "20%",
      visual: "early-number|caption=Percentage decrease is change divided by original, then multiplied by 100.|numbers=£420 - £336 = £84,£84 / £420 x 100 = 20%",
      misconceptionTargets: ["percentage-change-error", "original-amount-error"],
    },
    {
      cluster: "percentages-and-discounts",
      clusterTitle: "Percentages and discounts",
      title: "Game percentage increase",
      prompt: "A shop increases the price of a game from £28 to £33.60. What is the percentage increase?",
      options: ["20%", "5.6%", "25%", "15%"],
      answer: "20%",
      visual: "early-number|caption=Percentage increase is change divided by original, then multiplied by 100.|numbers=£33.60 - £28 = £5.60,£5.60 / £28 x 100 = 20%",
      misconceptionTargets: ["percentage-change-error", "increase-direction-error"],
    },
    {
      cluster: "percentages-and-discounts",
      clusterTitle: "Percentages and discounts",
      title: "Successive laptop discount",
      prompt: "A laptop costs £750. A store offers 15% off and then an extra 5% off the sale price. What is the final price?",
      options: ["£605.63", "£600.00", "£637.50", "£612.50"],
      answer: "£605.63",
      visual: "early-number|caption=Successive discounts are multiplied, not added.|numbers=£750 x 0.85 x 0.95,£605.63",
      misconceptionTargets: ["successive-percentage-error", "rounding-money-error"],
    },
    {
      cluster: "multi-step-modelling",
      clusterTitle: "Multi-step modelling",
      title: "Road trip distance",
      prompt: "A family drives 420 km on the first day and 380 km on the second day. They still have 250 km left. What is the total distance of the trip?",
      options: ["1,050 km", "800 km", "950 km", "1,250 km"],
      answer: "1,050 km",
      visual: "early-number|caption=Add each part of the trip distance.|numbers=420 km + 380 km + 250 km,1,050 km",
      misconceptionTargets: ["operation-choice-error", "multi-step-context-error"],
    },
    {
      cluster: "multi-step-modelling",
      clusterTitle: "Multi-step modelling",
      title: "Cafe weekend profit",
      prompt: "A cafe makes £320 in sales on Saturday and £900 on Sunday. It spends £420 on ingredients and £190 on staff costs. How much profit does it make over the weekend?",
      options: ["£610", "£1,220", "£710", "£290"],
      answer: "£610",
      visual: "early-number|caption=Profit is income minus costs.|numbers=income £1,220,costs £610,profit £610",
      misconceptionTargets: ["profit-cost-error", "multi-step-money-error"],
    },
    {
      cluster: "percentages-and-discounts",
      clusterTitle: "Percentages and discounts",
      title: "Simple interest",
      prompt: "Sam invests £2,000 in an account that earns 4% interest per year. How much interest will he earn in 3 years?",
      options: ["£240", "£80", "£2,240", "£120"],
      answer: "£240",
      visual: "early-number|caption=Simple interest adds the same amount each year.|numbers=4% of £2000 = £80,£80 x 3 = £240",
      misconceptionTargets: ["simple-interest-error", "interest-vs-total-error"],
    },
    {
      cluster: "multi-step-modelling",
      clusterTitle: "Multi-step modelling",
      title: "Buses and total cost",
      prompt: "A school bus can carry 28 students. There are 86 students going on a trip. Each student pays £5 for the bus. How many buses are needed and how much is collected in total?",
      options: ["4 buses and £430", "3 buses and £430", "4 buses and £400", "3 buses and £420"],
      answer: "4 buses and £430",
      visual: "early-number|caption=Round up the number of buses, then find the total collected.|numbers=86 / 28 is more than 3,4 buses,86 x £5 = £430",
      misconceptionTargets: ["rounding-context-error", "multi-step-money-error"],
    },
    {
      cluster: "multi-step-modelling",
      clusterTitle: "Multi-step modelling",
      title: "Class event budget",
      prompt: "A class event has a total budget of £200. The class spends £85 on food, £45 on decorations and £38 on prizes. How much money is left?",
      options: ["£32", "£168", "£42", "£28"],
      answer: "£32",
      visual: "early-number|caption=Subtract every cost from the total budget.|numbers=£200 - £85 - £45 - £38,£32",
      misconceptionTargets: ["budgeting-subtraction-error", "multi-step-money-error"],
    },
    {
      cluster: "real-world-decision-making",
      clusterTitle: "Real-world decision-making",
      title: "Savings model",
      prompt: "You want to save £300 in 6 months. How much should you save each month?",
      options: ["£50", "£60", "£30", "£300"],
      answer: "£50",
      visual: "early-number|caption=Divide the total saving target equally across the months.|numbers=£300 / 6,£50 per month",
      misconceptionTargets: ["rate-error", "savings-model-error"],
    },
    {
      cluster: "real-world-decision-making",
      clusterTitle: "Real-world decision-making",
      title: "Choose the best model",
      prompt: "Which is the best first step when solving a real-world modelling problem?",
      options: ["Identify what is known and what needs to be found", "Guess the answer first", "Ignore units", "Use every number without thinking"],
      answer: "Identify what is known and what needs to be found",
      visual: "early-number|caption=Good modelling starts by organising the information and the goal.|numbers=known values,unknown value,units",
      misconceptionTargets: ["modelling-process-error", "reasonableness-check-error"],
    },
  ];
}

function accuracySeeds(): Seed[] {
  return [
    {
      cluster: "decimal-place-rounding",
      clusterTitle: "Decimal-place rounding",
      title: "Round to 1 decimal place",
      prompt: "Round 23.4567 to 1 decimal place.",
      options: ["23.5", "23.4", "23.46", "23"],
      answer: "23.5",
      visual: "early-number|caption=Look at the digit immediately after the place being rounded.|numbers=23.4567,1 decimal place,23.5",
      misconceptionTargets: ["rounding-boundary-error", "decimal-place-error"],
    },
    {
      cluster: "decimal-place-rounding",
      clusterTitle: "Decimal-place rounding",
      title: "Round to 2 decimal places",
      prompt: "Round 19.842 to 2 decimal places.",
      options: ["19.84", "19.85", "19.8", "20.00"],
      answer: "19.84",
      visual: "early-number|caption=The third decimal digit decides whether the hundredths digit changes.|numbers=19.842,2 decimal places,19.84",
      misconceptionTargets: ["rounding-boundary-error", "decimal-place-error"],
    },
    {
      cluster: "decimal-place-rounding",
      clusterTitle: "Decimal-place rounding",
      title: "Round a small decimal",
      prompt: "Round 0.98765 to 3 decimal places.",
      options: ["0.988", "0.987", "0.990", "0.986"],
      answer: "0.988",
      visual: "early-number|caption=Keep three decimal places, then use the next digit to round.|numbers=0.98765,3 decimal places,0.988",
      misconceptionTargets: ["rounding-boundary-error", "decimal-place-error"],
    },
    {
      cluster: "decimal-place-rounding",
      clusterTitle: "Decimal-place rounding",
      title: "Round without carrying",
      prompt: "Round 9.9954 to 3 decimal places.",
      options: ["9.995", "9.996", "10.000", "9.99"],
      answer: "9.995",
      visual: "early-number|caption=The fourth decimal digit is 4, so the thousandths digit stays the same.|numbers=9.9954,3 decimal places,9.995",
      misconceptionTargets: ["rounding-boundary-error", "carrying-rounding-error"],
    },
    {
      cluster: "significant-figures",
      clusterTitle: "Significant figures",
      title: "Small number to 2 significant figures",
      prompt: "Round 0.0037856 to 2 significant figures.",
      options: ["0.0038", "0.0037", "0.004", "0.00378"],
      answer: "0.0038",
      visual: "early-number|caption=Count significant figures from the first non-zero digit.|numbers=0.0037856,2 significant figures,0.0038",
      misconceptionTargets: ["significant-figures-error", "leading-zero-error"],
    },
    {
      cluster: "significant-figures",
      clusterTitle: "Significant figures",
      title: "Decimal to 3 significant figures",
      prompt: "Round 45.678 to 3 significant figures.",
      options: ["45.7", "45.6", "46.0", "45.68"],
      answer: "45.7",
      visual: "early-number|caption=Keep three significant digits, then use the next digit to round.|numbers=45.678,3 significant figures,45.7",
      misconceptionTargets: ["significant-figures-error", "rounding-boundary-error"],
    },
    {
      cluster: "significant-figures",
      clusterTitle: "Significant figures",
      title: "Whole number to 4 significant figures",
      prompt: "Round 1234.567 to 4 significant figures.",
      options: ["1235", "1234", "1230", "1234.5"],
      answer: "1235",
      visual: "early-number|caption=The fifth significant digit is 5, so round the fourth digit up.|numbers=1234.567,4 significant figures,1235",
      misconceptionTargets: ["significant-figures-error", "rounding-boundary-error"],
    },
    {
      cluster: "significant-figures",
      clusterTitle: "Significant figures",
      title: "Very small number to 2 significant figures",
      prompt: "Round 0.0004567 to 2 significant figures.",
      options: ["0.00046", "0.00045", "0.0005", "0.000456"],
      answer: "0.00046",
      visual: "early-number|caption=Leading zeros are not significant; count from 4.|numbers=0.0004567,2 significant figures,0.00046",
      misconceptionTargets: ["significant-figures-error", "leading-zero-error"],
    },
    {
      cluster: "limits-of-accuracy",
      clusterTitle: "Lower and upper bounds",
      title: "Lower bound to nearest 0.01 cm",
      prompt: "A length is 12.36 cm correct to the nearest 0.01 cm. What is the lower bound?",
      options: ["12.355 cm", "12.35 cm", "12.365 cm", "12.305 cm"],
      answer: "12.355 cm",
      visual: "early-number|caption=Half of 0.01 cm is 0.005 cm. Subtract it for the lower bound.|numbers=12.36 cm - 0.005 cm,12.355 cm",
      misconceptionTargets: ["bounds-half-unit-error", "lower-upper-bound-error"],
    },
    {
      cluster: "limits-of-accuracy",
      clusterTitle: "Lower and upper bounds",
      title: "Upper bound to nearest 0.01 cm",
      prompt: "A length is 12.36 cm correct to the nearest 0.01 cm. What is the upper bound?",
      options: ["12.365 cm", "12.355 cm", "12.37 cm", "12.36 cm"],
      answer: "12.365 cm",
      visual: "early-number|caption=Half of 0.01 cm is 0.005 cm. Add it for the upper bound.|numbers=12.36 cm + 0.005 cm,12.365 cm",
      misconceptionTargets: ["bounds-half-unit-error", "lower-upper-bound-error"],
    },
    {
      cluster: "limits-of-accuracy",
      clusterTitle: "Lower and upper bounds",
      title: "Mass bounds",
      prompt: "A mass is 2.5 kg correct to the nearest 0.1 kg. What are the lower and upper bounds?",
      options: ["2.45 kg and 2.55 kg", "2.4 kg and 2.6 kg", "2.0 kg and 3.0 kg", "2.49 kg and 2.51 kg"],
      answer: "2.45 kg and 2.55 kg",
      visual: "early-number|caption=Half of 0.1 kg is 0.05 kg.|numbers=2.5 - 0.05,2.5 + 0.05,2.45 kg to 2.55 kg",
      misconceptionTargets: ["bounds-half-unit-error", "accuracy-interval-error"],
    },
    {
      cluster: "limits-of-accuracy",
      clusterTitle: "Lower and upper bounds",
      title: "Distance bounds",
      prompt: "A distance is 125 m correct to the nearest 10 m. What are the lower and upper bounds?",
      options: ["120 m and 130 m", "124.5 m and 125.5 m", "115 m and 135 m", "125 m and 135 m"],
      answer: "120 m and 130 m",
      visual: "early-number|caption=Half of 10 m is 5 m, so move 5 m either side of 125 m.|numbers=125 - 5,125 + 5,120 m to 130 m",
      misconceptionTargets: ["bounds-half-unit-error", "nearest-ten-error"],
    },
    {
      cluster: "limits-of-accuracy",
      clusterTitle: "Lower and upper bounds",
      title: "Time bounds",
      prompt: "A time is 36 s correct to the nearest 5 s. What are the lower and upper bounds?",
      options: ["33.5 s and 38.5 s", "35 s and 40 s", "31 s and 41 s", "34 s and 38 s"],
      answer: "33.5 s and 38.5 s",
      visual: "early-number|caption=Half of 5 seconds is 2.5 seconds.|numbers=36 - 2.5,36 + 2.5,33.5 s to 38.5 s",
      misconceptionTargets: ["bounds-half-unit-error", "time-accuracy-error"],
    },
    {
      cluster: "calculation-and-rounding",
      clusterTitle: "Calculate then round",
      title: "Add then round",
      prompt: "Calculate 23.456 + 7.891 and round the final answer to 2 decimal places.",
      options: ["31.35", "31.34", "31.347", "31.3"],
      answer: "31.35",
      visual: "early-number|caption=Calculate first, then round the final answer.|numbers=23.456 + 7.891 = 31.347,2 decimal places,31.35",
      misconceptionTargets: ["premature-rounding-error", "decimal-place-error"],
    },
    {
      cluster: "calculation-and-rounding",
      clusterTitle: "Calculate then round",
      title: "Subtract then round",
      prompt: "Calculate 19.87 - 4.326 and round the final answer to 2 decimal places.",
      options: ["15.54", "15.55", "15.544", "15.5"],
      answer: "15.54",
      visual: "early-number|caption=Do the subtraction first, then round the result.|numbers=19.87 - 4.326 = 15.544,2 decimal places,15.54",
      misconceptionTargets: ["premature-rounding-error", "subtraction-decimal-error"],
    },
    {
      cluster: "calculation-and-rounding",
      clusterTitle: "Calculate then round",
      title: "Multiply then round",
      prompt: "Calculate 3.456 × 1.89 and round the final answer to 3 significant figures.",
      options: ["6.53", "6.532", "6.54", "6.5"],
      answer: "6.53",
      visual: "early-number|caption=Multiply first, then round to the requested significant figures.|numbers=3.456 x 1.89 = 6.53184,3 significant figures,6.53",
      misconceptionTargets: ["premature-rounding-error", "significant-figures-error"],
    },
    {
      cluster: "calculation-and-rounding",
      clusterTitle: "Calculate then round",
      title: "Divide then round",
      prompt: "Calculate 45.67 ÷ 2.3 and round the final answer to 2 decimal places.",
      options: ["19.86", "19.85", "19.9", "20.00"],
      answer: "19.86",
      visual: "early-number|caption=Divide first, then round the final answer.|numbers=45.67 / 2.3 = 19.8565...,2 decimal places,19.86",
      misconceptionTargets: ["premature-rounding-error", "decimal-place-error"],
    },
    {
      cluster: "real-world-accuracy",
      clusterTitle: "Real-world accuracy",
      title: "Runner lower bound",
      prompt: "A runner completes a race in 45.678 seconds. The time is recorded to the nearest 0.01 seconds. What is the lower bound?",
      options: ["45.675 s", "45.67 s", "45.685 s", "45.678 s"],
      answer: "45.675 s",
      visual: "early-number|caption=Use the recorded time to the nearest 0.01 seconds, then subtract 0.005 seconds.|numbers=45.68 s - 0.005 s,45.675 s",
      misconceptionTargets: ["bounds-half-unit-error", "real-world-accuracy-error"],
    },
    {
      cluster: "real-world-accuracy",
      clusterTitle: "Real-world accuracy",
      title: "Runner upper bound",
      prompt: "A runner completes a race in 45.678 seconds. The time is recorded to the nearest 0.01 seconds. What is the upper bound?",
      options: ["45.685 s", "45.675 s", "45.68 s", "45.688 s"],
      answer: "45.685 s",
      visual: "early-number|caption=Use the recorded time to the nearest 0.01 seconds, then add 0.005 seconds.|numbers=45.68 s + 0.005 s,45.685 s",
      misconceptionTargets: ["bounds-half-unit-error", "real-world-accuracy-error"],
    },
    {
      cluster: "real-world-accuracy",
      clusterTitle: "Real-world accuracy",
      title: "Petrol reading",
      prompt: "A petrol pump shows 23.478 litres in a car's tank. The reading is correct to 3 significant figures. What is the value to the nearest litre?",
      options: ["23 litres", "24 litres", "23.5 litres", "20 litres"],
      answer: "23 litres",
      visual: "early-number|caption=Round the reading to the nearest whole litre.|numbers=23.478 litres,nearest litre,23 litres",
      misconceptionTargets: ["rounding-context-error", "units-error"],
    },
    {
      cluster: "real-world-accuracy",
      clusterTitle: "Real-world accuracy",
      title: "Greatest possible mass",
      prompt: "A shop buys 248.6 kg of rice. The mass is correct to the nearest 0.1 kg. What is the greatest possible mass?",
      options: ["248.65 kg", "248.60 kg", "248.55 kg", "248.7 kg"],
      answer: "248.65 kg",
      visual: "early-number|caption=The upper bound is half of 0.1 kg above the rounded mass.|numbers=248.6 + 0.05,248.65 kg",
      misconceptionTargets: ["bounds-half-unit-error", "greatest-possible-value-error"],
    },
    {
      cluster: "estimation-and-checking",
      clusterTitle: "Estimation and checking",
      title: "Estimate a product",
      prompt: "Estimate 98.6 × 19.8 by rounding each number to 1 significant figure first.",
      options: ["2,000", "200", "20,000", "1,800"],
      answer: "2,000",
      visual: "early-number|caption=Round to easy numbers, then multiply.|numbers=98.6 rounds to 100,19.8 rounds to 20,100 x 20 = 2,000",
      misconceptionTargets: ["estimation-error", "place-value-scaling-error"],
    },
    {
      cluster: "estimation-and-checking",
      clusterTitle: "Estimation and checking",
      title: "Check reasonableness",
      prompt: "A calculation gives 24,980.1. A student rounds the answer to 370 correct to 1 decimal place. Is this reasonable?",
      options: ["No", "Yes"],
      answer: "No",
      visual: "early-number|caption=The rounded answer should stay close to the original value.|numbers=24,980.1,370,not reasonable",
      misconceptionTargets: ["reasonableness-check-error", "rounding-scale-error"],
    },
    {
      cluster: "significant-figures",
      clusterTitle: "Significant figures",
      title: "Round to 1 significant figure",
      prompt: "A calculation gives 0.000932. Round this to 1 significant figure.",
      options: ["0.0009", "0.001", "0.00093", "0.00009"],
      answer: "0.0009",
      visual: "early-number|caption=Count from the first non-zero digit, then round to one significant figure.|numbers=0.000932,1 significant figure,0.0009",
      misconceptionTargets: ["significant-figures-error", "leading-zero-error"],
    },
  ];
}

function strategySeeds(): Seed[] {
  return [
    {
      cluster: "whole-number-strategies",
      clusterTitle: "Whole-number strategies",
      title: "Compatible numbers strategy",
      prompt: "Which strategy is most efficient for 448 + 497 + 652?",
      options: ["Compatible numbers", "Long division", "Use a pie chart", "Guess and check"],
      answer: "Compatible numbers",
      visual: "early-number|caption=Look for numbers that combine neatly before calculating.|numbers=448 + 652 = 1100,1100 + 497 = 1597",
      misconceptionTargets: ["inefficient-strategy-choice", "compatible-numbers-gap"],
    },
    {
      cluster: "whole-number-strategies",
      clusterTitle: "Whole-number strategies",
      title: "Compatible numbers calculation",
      prompt: "Calculate efficiently: 448 + 497 + 652.",
      options: ["1,597", "1,497", "1,607", "1,697"],
      answer: "1,597",
      visual: "early-number|caption=Pair 448 and 652 first because they make 1,100.|numbers=448 + 652,1100 + 497,1597",
      misconceptionTargets: ["compatible-numbers-gap", "addition-place-value-error"],
    },
    {
      cluster: "rounding-and-adjusting",
      clusterTitle: "Rounding and adjusting",
      title: "Near-friendly multiplication",
      prompt: "Which strategy is most efficient for 25 × 198?",
      options: ["Calculate 25 × 200, then subtract 25 × 2", "Add 25 and 198", "Use long division", "Round the final answer only"],
      answer: "Calculate 25 × 200, then subtract 25 × 2",
      visual: "early-number|caption=Use a nearby friendly number, then adjust the extra amount.|numbers=25 x 200,subtract 25 x 2,4950",
      misconceptionTargets: ["rounding-adjusting-error", "operation-choice-error"],
    },
    {
      cluster: "rounding-and-adjusting",
      clusterTitle: "Rounding and adjusting",
      title: "Near-friendly multiplication answer",
      prompt: "Calculate efficiently: 25 × 198.",
      options: ["4,950", "5,000", "4,850", "5,050"],
      answer: "4,950",
      visual: "early-number|caption=25 x 198 = 25 x 200 - 25 x 2.|numbers=5000 - 50,4950",
      misconceptionTargets: ["rounding-adjusting-error", "multiplication-fact-error"],
    },
    {
      cluster: "known-facts",
      clusterTitle: "Known facts",
      title: "Use 125 facts",
      prompt: "Which strategy is most efficient for 125 × 64?",
      options: ["Use 125 × 8 = 1,000, then multiply by 8", "Add 125 and 64", "Round 64 to 60 and stop", "Use subtraction"],
      answer: "Use 125 × 8 = 1,000, then multiply by 8",
      visual: "early-number|caption=Break 64 into 8 x 8 so a known fact creates 1,000.|numbers=125 x 8 = 1000,1000 x 8 = 8000",
      misconceptionTargets: ["known-facts-gap", "factorisation-error"],
    },
    {
      cluster: "split-and-rearrange",
      clusterTitle: "Split and rearrange",
      title: "Distributive strategy",
      prompt: "Which strategy is most efficient for 48 × 203 + 52 × 203?",
      options: ["Combine 48 and 52 first, then multiply by 203", "Multiply 48 × 203 and 52 × 203 separately", "Divide by 203", "Subtract 52 from 48"],
      answer: "Combine 48 and 52 first, then multiply by 203",
      visual: "early-number|caption=Use the shared factor 203 to combine the two parts first.|numbers=(48 + 52) x 203,100 x 203,20300",
      misconceptionTargets: ["distributive-thinking-gap", "inefficient-strategy-choice"],
    },
    {
      cluster: "fractions-and-decimals",
      clusterTitle: "Fractions and decimals",
      title: "Fraction strategy",
      prompt: "Which strategy is most efficient for 3/4 + 2/5 + 1/4?",
      options: ["Combine 3/4 and 1/4 first", "Convert everything to decimals first", "Multiply all numerators", "Ignore the denominators"],
      answer: "Combine 3/4 and 1/4 first",
      visual: "early-number|caption=Combine like denominators first to make a whole.|numbers=3/4 + 1/4 = 1,1 + 2/5 = 1 2/5",
      misconceptionTargets: ["fraction-strategy-error", "common-denominator-gap"],
    },
    {
      cluster: "fractions-and-decimals",
      clusterTitle: "Fractions and decimals",
      title: "Fraction calculation",
      prompt: "Calculate efficiently: 3/4 + 2/5 + 1/4.",
      options: ["1 2/5", "1 1/5", "6/13", "1 1/4"],
      answer: "1 2/5",
      visual: "early-number|caption=3/4 and 1/4 make 1, then add 2/5.|numbers=3/4 + 1/4,1 + 2/5,1 2/5",
      misconceptionTargets: ["fraction-addition-error", "compatible-fractions-gap"],
    },
    {
      cluster: "fractions-and-decimals",
      clusterTitle: "Fractions and decimals",
      title: "Divide by a quarter",
      prompt: "Which strategy is most efficient for 7.2 ÷ 0.25?",
      options: ["Divide by 0.25 by multiplying by 4", "Divide by 25", "Multiply by 0.25", "Round 7.2 to 7 and stop"],
      answer: "Divide by 0.25 by multiplying by 4",
      visual: "early-number|caption=Dividing by one quarter is the same as multiplying by 4.|numbers=7.2 x 4,28.8",
      misconceptionTargets: ["decimal-division-error", "equivalent-value-gap"],
    },
    {
      cluster: "fractions-and-decimals",
      clusterTitle: "Fractions and decimals",
      title: "Divide by a quarter answer",
      prompt: "Calculate efficiently: 7.2 ÷ 0.25.",
      options: ["28.8", "1.8", "18", "288"],
      answer: "28.8",
      visual: "early-number|caption=Use the equivalent operation 7.2 x 4.|numbers=7.2 x 4,28.8",
      misconceptionTargets: ["decimal-division-error", "place-value-scaling-error"],
    },
    {
      cluster: "fractions-and-decimals",
      clusterTitle: "Fractions and decimals",
      title: "Decimal multiplication strategy",
      prompt: "Which strategy is most efficient for 2.5 × 1.6?",
      options: ["Use 25 × 16, then divide by 100", "Add 2.5 and 1.6", "Round both numbers and stop", "Use long division"],
      answer: "Use 25 × 16, then divide by 100",
      visual: "early-number|caption=Scale to whole numbers, multiply, then scale back.|numbers=25 x 16 = 400,400 / 100 = 4",
      misconceptionTargets: ["decimal-place-value-error", "strategy-choice-error"],
    },
    {
      cluster: "mixed-operations",
      clusterTitle: "Mixed operations",
      title: "Order of operations first step",
      prompt: "Which should be done first in 48 - 15 + 6 × 27?",
      options: ["6 × 27", "48 - 15", "15 + 6", "48 - 27"],
      answer: "6 × 27",
      visual: "early-number|caption=Multiplication is completed before addition and subtraction.|numbers=6 x 27 first,then 48 - 15 + 162",
      misconceptionTargets: ["order-of-operations-error", "left-to-right-error"],
    },
    {
      cluster: "mixed-operations",
      clusterTitle: "Mixed operations",
      title: "Mixed operations answer",
      prompt: "Calculate: 48 - 15 + 6 × 27.",
      options: ["195", "891", "33", "162"],
      answer: "195",
      visual: "early-number|caption=Do multiplication first, then addition and subtraction from left to right.|numbers=6 x 27 = 162,48 - 15 + 162 = 195",
      misconceptionTargets: ["order-of-operations-error", "calculation-error"],
    },
    {
      cluster: "mixed-operations",
      clusterTitle: "Mixed operations",
      title: "Brackets and fractions",
      prompt: "Calculate: (75 - 28) × 6 ÷ 36 + 4.",
      options: ["11 5/6", "12", "47", "8"],
      answer: "11 5/6",
      visual: "early-number|caption=Use brackets first, then multiply and divide before adding.|numbers=75 - 28 = 47,47 x 6 / 36 = 47/6,47/6 + 4 = 11 5/6",
      misconceptionTargets: ["order-of-operations-error", "fraction-simplification-error"],
    },
    {
      cluster: "algebraic-strategies",
      clusterTitle: "Algebraic strategies",
      title: "Collect like terms",
      prompt: "Simplify: 4x + 7x - 5x.",
      options: ["6x", "16x", "-8x", "6"],
      answer: "6x",
      visual: "early-number|caption=Collect the x terms by combining their coefficients.|numbers=4x + 7x = 11x,11x - 5x = 6x",
      misconceptionTargets: ["like-terms-error", "coefficient-error"],
    },
    {
      cluster: "algebraic-strategies",
      clusterTitle: "Algebraic strategies",
      title: "Expand and simplify",
      prompt: "Simplify: 3(a + 5) - 2(a - 4).",
      options: ["a + 23", "5a + 7", "a + 7", "5a + 23"],
      answer: "a + 23",
      visual: "early-number|caption=Expand brackets, then collect like terms.|numbers=3a + 15 - 2a + 8,a + 23",
      misconceptionTargets: ["bracket-expansion-error", "like-terms-error"],
    },
    {
      cluster: "algebraic-strategies",
      clusterTitle: "Algebraic strategies",
      title: "Distributive algebra",
      prompt: "Simplify: 2(x - 3) + 4(x + 1).",
      options: ["6x - 2", "6x + 10", "2x - 2", "6x - 10"],
      answer: "6x - 2",
      visual: "early-number|caption=Expand both brackets before collecting like terms.|numbers=2x - 6 + 4x + 4,6x - 2",
      misconceptionTargets: ["bracket-expansion-error", "like-terms-error"],
    },
    {
      cluster: "algebraic-strategies",
      clusterTitle: "Algebraic strategies",
      title: "Substitution strategy",
      prompt: "Evaluate efficiently when x = 4: (x + 6)^2.",
      options: ["100", "40", "20", "64"],
      answer: "100",
      visual: "early-number|caption=Substitute first, then square the friendly value.|numbers=4 + 6 = 10,10^2 = 100",
      misconceptionTargets: ["substitution-error", "powers-error"],
    },
    {
      cluster: "real-world-strategies",
      clusterTitle: "Real-world strategies",
      title: "Pen packs",
      prompt: "A shop sells packs of 25 pens. A school buys 18 packs. How many pens does it buy?",
      options: ["450", "100", "72", "425"],
      answer: "450",
      visual: "early-number|caption=Use 25 x 4 = 100 or split 18 into friendly parts.|numbers=18 x 25,450 pens",
      misconceptionTargets: ["real-world-operation-error", "multiplication-strategy-error"],
    },
    {
      cluster: "real-world-strategies",
      clusterTitle: "Real-world strategies",
      title: "Recipe scaling",
      prompt: "A recipe uses 125 kg of flour for 1 batch. How much flour is needed for 6 batches?",
      options: ["750 kg", "625 kg", "131 kg", "725 kg"],
      answer: "750 kg",
      visual: "early-number|caption=Scale the amount for one batch by the number of batches.|numbers=125 x 6,750 kg",
      misconceptionTargets: ["scaling-error", "units-error"],
    },
    {
      cluster: "real-world-strategies",
      clusterTitle: "Real-world strategies",
      title: "Speed strategy",
      prompt: "A car travels 315 km in 5 hours. At the same speed, how far will it travel in 8.5 hours?",
      options: ["535.5 km", "504 km", "267.75 km", "630 km"],
      answer: "535.5 km",
      visual: "early-number|caption=Find the unit rate first, then multiply by the new time.|numbers=315 / 5 = 63 km/h,63 x 8.5 = 535.5 km",
      misconceptionTargets: ["rate-error", "real-world-operation-error"],
    },
    {
      cluster: "real-world-strategies",
      clusterTitle: "Real-world strategies",
      title: "Percentage reduction",
      prompt: "A computer is reduced from £860 to £688. What is the percentage reduction?",
      options: ["20%", "25%", "172%", "15%"],
      answer: "20%",
      visual: "early-number|caption=Find the reduction, then compare it with the original price.|numbers=860 - 688 = 172,172 / 860 x 100 = 20%",
      misconceptionTargets: ["percentage-change-error", "original-amount-error"],
    },
    {
      cluster: "which-strategy",
      clusterTitle: "Which strategy?",
      title: "Compatible number choice",
      prompt: "Which strategy is most efficient for 199 + 398 + 401?",
      options: ["Compatible numbers", "Standard algorithm only", "Long division", "Fraction conversion"],
      answer: "Compatible numbers",
      visual: "early-number|caption=Pair values that make a friendly total.|numbers=199 + 401 = 600,600 + 398 = 998",
      misconceptionTargets: ["compatible-numbers-gap", "inefficient-strategy-choice"],
    },
    {
      cluster: "which-strategy",
      clusterTitle: "Which strategy?",
      title: "Use factors of 100",
      prompt: "Which strategy is most efficient for 25 × 48?",
      options: ["Use 100 × 12 or 25 × 4 × 12", "Use long subtraction", "Convert to a percentage", "Use a graph"],
      answer: "Use 100 × 12 or 25 × 4 × 12",
      visual: "early-number|caption=Use 25 x 4 = 100, then multiply by 12.|numbers=48 = 4 x 12,25 x 4 x 12 = 1200",
      misconceptionTargets: ["factorisation-error", "known-facts-gap"],
    },
    {
      cluster: "challenge-strategies",
      clusterTitle: "Challenge strategies",
      title: "Split a factor",
      prompt: "Which strategy is most efficient for 1,234 × 37?",
      options: ["Split 37 into 40 - 3", "Add 1,234 and 37", "Divide by 37", "Round both numbers and stop"],
      answer: "Split 37 into 40 - 3",
      visual: "early-number|caption=Use a nearby multiple of ten and adjust.|numbers=1234 x 40,subtract 1234 x 3",
      misconceptionTargets: ["rounding-adjusting-error", "operation-choice-error"],
    },
    {
      cluster: "challenge-strategies",
      clusterTitle: "Challenge strategies",
      title: "Challenge expression",
      prompt: "Simplify or calculate efficiently: (2.4 + 3.6) × 25 - 15.5.",
      options: ["134.5", "150.5", "6", "165.5"],
      answer: "134.5",
      visual: "early-number|caption=Use the friendly sum before multiplying.|numbers=2.4 + 3.6 = 6,6 x 25 = 150,150 - 15.5 = 134.5",
      misconceptionTargets: ["order-of-operations-error", "decimal-calculation-error"],
    },
  ];
}

function reasoningSeeds(): Seed[] {
  const rows = [
    ["Why is 0.4 bigger than 0.35?", "Four tenths is more than thirty-five hundredths"],
    ["Why does 6 x 18 equal 108?", "6 x 20 minus 6 x 2"],
    ["Why is 3/4 the same as 75%?", "75 out of 100 is three quarters"],
    ["Why can sqrt(50) be 5sqrt(2)?", "50 has factor 25"],
    ["Which check supports 23 x 19 = 437?", "23 x 20 - 23"],
    ["Why is a 20% discount on $90 equal $18?", "10% is $9, so 20% is $18"],
    ["Why is -3 less than 1?", "-3 is left of 1 on the number line"],
    ["Which reason supports rounding 498 to 500?", "498 is close to 500"],
    ["Why keep pi exact?", "Rounding pi can lose precision"],
    ["Why is ratio 2:3 not the same as difference 1?", "Ratio compares multiplicatively"],
    ["Which explanation fits 2^-2 = 1/4?", "Negative powers make reciprocal powers"],
    ["Why are estimates useful?", "They check if answers are reasonable"],
  ];
  return rows.map(([question, answer], index) => ({
    cluster: index % 4 === 0 ? "explain-place-value" : index % 4 === 1 ? "justify-operations" : index % 4 === 2 ? "compare-representations" : "reasonableness",
    clusterTitle: index % 4 === 0 ? "Explain place value" : index % 4 === 1 ? "Justify operations" : index % 4 === 2 ? "Compare representations" : "Reasonableness",
    title: `Reasoning ${index + 1}`,
    prompt: `${question} Which explanation is best?`,
    options: [answer, "Because it looks bigger", "Because the answer is always the first number"],
    answer,
    visual: `early-number|caption=Use explanation cards to match claim and reason.|numbers=${question},${answer}`,
    misconceptionTargets: ["reasoning-without-evidence", "representation-connection-gap"],
  }));
}

export const NUMBER_YEARS_9_10_STEP_ASSESSMENTS = [
  defineStep(51, "Work with standard form and very large or very small numbers", "Standard form", "Represent scale efficiently when ordinary notation becomes awkward.", powersParent, standardFormSeeds()),
  defineStep(52, "Use powers, roots and indices in context", "Powers roots indices", "Apply exponential and inverse ideas in calculations and mathematical models.", powersParent, powersRootsSeeds()),
  defineStep(53, "Calculate exactly with fractions and multiples of pi where appropriate", "Exact fractions and pi", "Preserve exact values when estimation would lose important structure.", surdsParent, exactFormSeeds()),
  defineStep(54, "Work with percentage change, growth and decay", "Percentage change", "Reason about increase, decrease, and repeated change in practical settings.", percentParent, percentageChangeSeeds()),
  defineStep(55, "Apply ratio, proportion and rates of change", "Ratio proportion rates", "Use multiplicative thinking in more demanding financial, graphical, and scientific contexts.", percentParent, ratioRateSeeds()),
  defineStep(56, "Use number skills in algebraic and graphical contexts", "Number in algebra and graphs", "Bring numerical fluency into equations, graphs, and coordinate reasoning.", integersParent, algebraGraphSeeds()),
  defineStep(57, "Solve financial and real-world modelling problems", "Financial modelling", "Use mathematics to compare options, justify decisions, and interpret outcomes.", percentParent, financialModellingSeeds()),
  defineStep(58, "Interpret limits of accuracy and rounding", "Accuracy and rounding", "Understand how measurement, rounding, and approximation affect conclusions.", approximationParent, accuracySeeds()),
  defineStep(59, "Select efficient calculation strategies for unfamiliar problems", "Efficient strategies", "Choose, adapt, and combine methods when the answer path is not obvious.", rationalParent, strategySeeds()),
  defineStep(60, "Justify and communicate mathematical reasoning", "Mathematical reasoning", "Explain methods clearly, compare approaches, and defend conclusions with evidence.", rationalParent, reasoningSeeds()),
] as const satisfies Years910StepAssessmentDefinition[];

export const NUMBER_YEARS_9_10_STEP_ASSESSMENT_ITEMS =
  NUMBER_YEARS_9_10_STEP_ASSESSMENTS.flatMap((assessment) => assessment.items);
