import type { NumberPracticeTask } from "@/lib/clean/practice/numberPowersRootsPracticeModules";
import {
  NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_ASSESSMENT_KEY,
  NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_PATHWAY_STEP_ID,
  NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_STEP_KEY,
} from "@/lib/clean/assessments/numberStep1RecogniseSmallQuantitiesAssessmentItems";

export const NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_PRACTICE_KEY =
  "number-step-1-recognise-small-quantities-practice-v1";

function visual(description: string) {
  return {
    type: "context_card" as const,
    description,
  };
}

function task(
  id: string,
  title: string,
  prompt: string,
  options: string[],
  expectedAnswer: string,
  supportPrompt: string,
  workedSolution: string,
  visualDescription: string,
  misconceptionTargets: string[],
  relatedAssessmentItemIds: string[],
): NumberPracticeTask {
  return {
    id,
    title,
    prompt,
    taskType: "multiple_choice",
    options,
    expectedAnswer,
    acceptableAnswers: [expectedAnswer],
    supportPrompt,
    workedSolution,
    misconceptionTargets,
    relatedAssessmentItemIds,
    visualSupport: visual(visualDescription),
  };
}

export const NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_PRACTICE_TASKS: NumberPracticeTask[] = [
  task(
    "number-step-1-practice-001",
    "Quick-look two",
    "Look at the card without counting. It shows two counters. Which number matches?",
    ["1", "2", "3"],
    "2",
    "Try saying the amount straight away, then check by looking again.",
    "Two counters match the number 2.",
    "Quick-look card with two counters close together.",
    ["small-quantity-recognition-gap", "numeral-quantity-match-gap"],
    ["number-step-1-assess-005"],
  ),
  task(
    "number-step-1-practice-002",
    "Four corners",
    "A card has one counter near each corner. What number is shown?",
    ["3", "4", "5"],
    "4",
    "Notice the familiar four-corner pattern.",
    "One counter in each of four corners shows 4.",
    "Four counters in a dice-like corner pattern.",
    ["four-five-pattern-confusion"],
    ["number-step-1-assess-002"],
  ),
  task(
    "number-step-1-practice-003",
    "Same three",
    "Which group shows the same number as three counters in a row?",
    ["Three counters in a triangle", "Two counters far apart", "Four counters close together"],
    "Three counters in a triangle",
    "The shape can change, but the number of counters can stay the same.",
    "Both cards have three counters.",
    "Three comparison cards: row of three, triangle of three, spaced pair, close group of four.",
    ["arrangement-changes-quantity-error"],
    ["number-step-1-assess-011"],
  ),
  task(
    "number-step-1-practice-004",
    "Spacing does not add counters",
    "A card has four counters spread far apart. What number does it show?",
    ["4", "5", "More than 5"],
    "4",
    "Count the counters only in your eyes. The spaces are not extra counters.",
    "There are four counters, even though they are spread out.",
    "Four counters with wide spaces between them.",
    ["spacing-quantity-confusion"],
    ["number-step-1-assess-012"],
  ),
  task(
    "number-step-1-practice-005",
    "One at a glance",
    "A quick-look card shows one counter. Which number should you choose?",
    ["0", "1", "2"],
    "1",
    "One counter matches the number 1.",
    "The card has one counter.",
    "Single counter centred on a quick-look card.",
    ["small-quantity-recognition-gap"],
    ["number-step-1-assess-009"],
  ),
  task(
    "number-step-1-practice-006",
    "Five frame",
    "A five-frame card has all five spaces filled. Which number is shown?",
    ["4", "5", "6"],
    "5",
    "A full five-frame shows five.",
    "All five spaces are filled, so the answer is 5.",
    "Five-frame-like card with five filled spaces.",
    ["four-five-pattern-confusion"],
    ["number-step-1-assess-006"],
  ),
  task(
    "number-step-1-practice-007",
    "Find another four",
    "A card shows four counters in a line. Which group shows the same number?",
    ["Four counters in a square", "Three counters in a row", "Five counters spread out"],
    "Four counters in a square",
    "Look for the same number of counters, not the same shape.",
    "A line of four and a square of four both show 4.",
    "Comparison cards showing four in a line, four in a square, three in a row and five spread out.",
    ["arrangement-changes-quantity-error"],
    ["number-step-1-assess-007"],
  ),
  task(
    "number-step-1-practice-008",
    "Big and small counters",
    "Card A has two big counters. Card B has two small counters. Which card has more?",
    ["Card A", "Card B", "They are the same"],
    "They are the same",
    "Size does not change how many counters there are.",
    "Both cards have two counters.",
    "Two cards each showing two counters; one uses larger counters.",
    ["size-quantity-confusion"],
    ["number-step-1-assess-008"],
  ),
  task(
    "number-step-1-practice-009",
    "Three triangle",
    "A quick-look card shows three counters in a triangle. Which number matches?",
    ["2", "3", "4"],
    "3",
    "A triangle pattern with three corners often shows three.",
    "There are three counters.",
    "Three counters in a triangle arrangement.",
    ["small-quantity-recognition-gap"],
    ["number-step-1-assess-001"],
  ),
  task(
    "number-step-1-practice-010",
    "Five like dice",
    "A card shows four corner counters and one middle counter. What number is shown?",
    ["4", "5", "6"],
    "5",
    "This is the familiar dice pattern for five.",
    "Four corners plus one middle counter makes five counters.",
    "Dice-style five-dot card.",
    ["four-five-pattern-confusion"],
    ["number-step-1-assess-010"],
  ),
  task(
    "number-step-1-practice-011",
    "Same two, new places",
    "Which group shows the same number as two counters close together?",
    ["Two counters far apart", "Three counters close together", "One large counter"],
    "Two counters far apart",
    "The places can change. The number stays two.",
    "Two counters far apart still show 2.",
    "Comparison cards showing a close pair, a spaced pair, three close counters and one large counter.",
    ["spacing-quantity-confusion", "arrangement-changes-quantity-error"],
    ["number-step-1-assess-003"],
  ),
  task(
    "number-step-1-practice-012",
    "More spaces or more counters",
    "Card A has five counters close together. Card B has four counters spread out. Which has more counters?",
    ["Card A", "Card B", "They are the same"],
    "Card A",
    "Only count the counters, not the spaces.",
    "Five counters is more than four counters.",
    "Two cards: five close counters and four spread-out counters.",
    ["spacing-quantity-confusion"],
    ["number-step-1-assess-004"],
  ),
];

export const NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_PRACTICE_METADATA = {
  stepKey: NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_STEP_KEY,
  pathwayStepId: NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_PATHWAY_STEP_ID,
  relatedStepAssessmentKey: NUMBER_STEP_1_RECOGNISE_SMALL_QUANTITIES_ASSESSMENT_KEY,
};
