import type { DemoLearnerId } from "@/lib/demo/carterFamilyDemoData";

export type DemoEvidenceRecord = {
  id: string;
  learnerId: DemoLearnerId;
  title: string;
  shortDescription: string;
  learningArea: string;
  date: string;
  reflection?: string;
  includeInPortfolio: true;
  includeInReport: true;
  evidenceType: "Work sample" | "Observation" | "Photo and observation" | "Project summary";
  imageKey: string;
  imageAlt: string;
  imagePlaceholder: string;
  tags?: string[];
  curriculumNote?: string;
};

export const demoEvidenceDataset = {
  family: {
    name: "The Carter Family",
    parentDisplayName: "Sarah Carter",
    location: "North Carolina, USA",
    learningYear: "2025–2026 learning year",
    reportingPeriod: "March 2026",
  },
  learners: [
    { id: "emma", displayName: "Emma Carter", age: 8, grade: "Grade 3" },
    { id: "noah", displayName: "Noah Carter", age: 11, grade: "Grade 6" },
  ] satisfies Array<{ id: DemoLearnerId; displayName: string; age: number; grade: string }>,
  evidence: [
    {
      id: "demo-evidence-handwriting",
      learnerId: "emma",
      title: "Handwriting practice and a story beginning",
      shortDescription: "Emma copied a short paragraph, then added her own opening sentence for a story about a rainy-day garden.",
      learningArea: "Literacy",
      date: "2026-03-04",
      reflection: "Emma took care with letter formation and was proud of choosing the story details herself.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Work sample",
      imageKey: "demo-handwriting-loops",
      imageAlt: "A fictional child’s handwriting page beside a pencil and story notebook",
      imagePlaceholder: "Future sample image: handwriting and story notebook",
      tags: ["writing", "handwriting"],
      curriculumNote: "Writing fluency and communicating ideas",
    },
    {
      id: "demo-evidence-reading",
      learnerId: "emma",
      title: "Reading in the quiet corner",
      shortDescription: "Emma read a chapter aloud in the family reading nook and retold the main events in her own words.",
      learningArea: "Reading",
      date: "2026-03-06",
      reflection: "She noticed how the character’s choices changed the story and asked to read the next chapter independently.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Observation",
      imageKey: "demo-reading-nook",
      imageAlt: "A fictional reading nook with an open chapter book and a cushion",
      imagePlaceholder: "Future sample image: family reading nook",
      tags: ["reading", "oral retell"],
    },
    {
      id: "demo-evidence-maths-bears",
      learnerId: "emma",
      title: "Sorting maths bears into equal groups",
      shortDescription: "Emma used coloured counters to make equal groups and explained how the groups showed repeated addition.",
      learningArea: "Maths",
      date: "2026-03-09",
      reflection: "Emma changed her arrangement after checking the groups and explained why the total stayed the same.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Photo and observation",
      imageKey: "demo-maths-bears",
      imageAlt: "Fictional coloured counting bears arranged in equal groups on a table",
      imagePlaceholder: "Future sample image: maths manipulatives",
      tags: ["grouping", "number sense"],
      curriculumNote: "Equal groups and early multiplication thinking",
    },
    {
      id: "demo-evidence-counting",
      learnerId: "noah",
      title: "Counting and recording garden seeds",
      shortDescription: "Noah counted seed packets for the garden plan and recorded the totals in a simple table.",
      learningArea: "Maths",
      date: "2026-03-10",
      reflection: "He checked the total twice and noticed that the table made the comparison easier to see.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Work sample",
      imageKey: "demo-counting-seeds",
      imageAlt: "A fictional seed-counting table beside labelled garden seed packets",
      imagePlaceholder: "Future sample image: counting and recording activity",
      tags: ["counting", "data recording"],
    },
    {
      id: "demo-evidence-science-sprouts",
      learnerId: "emma",
      title: "Observing the first green sprouts",
      shortDescription: "Emma measured the bean sprouts, drew what she saw and compared today’s growth with last week’s notes.",
      learningArea: "Science",
      date: "2026-03-12",
      reflection: "Emma used the word ‘evidence’ when explaining why she thought the plant had grown toward the window.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Photo and observation",
      imageKey: "demo-science-sprouts",
      imageAlt: "Fictional bean sprouts in a jar beside a child’s labelled observation page",
      imagePlaceholder: "Future sample image: science sprout observation",
      tags: ["observation", "plants"],
      curriculumNote: "Noticing change and explaining observations",
    },
    {
      id: "demo-evidence-art",
      learnerId: "emma",
      title: "Watercolour garden study",
      shortDescription: "Emma made a watercolour study of leaves and mixed greens to match the plants she observed outside.",
      learningArea: "Art",
      date: "2026-03-13",
      reflection: "She tried two brush sizes and described how the smaller brush helped her add leaf details.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Work sample",
      imageKey: "demo-watercolour-garden",
      imageAlt: "A fictional child’s watercolour garden study with green leaves and a paint palette",
      imagePlaceholder: "Future sample image: watercolour garden study",
      tags: ["painting", "nature journal"],
    },
    {
      id: "demo-evidence-nature-walk",
      learnerId: "noah",
      title: "Nature walk field notes",
      shortDescription: "Noah recorded three signs of spring on a walk and grouped them as plant, animal or weather observations.",
      learningArea: "Science",
      date: "2026-03-16",
      reflection: "He returned to one observation to add a more precise description of the bird call.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Observation",
      imageKey: "demo-nature-walk",
      imageAlt: "A fictional field notebook with spring observations on a nature walk",
      imagePlaceholder: "Future sample image: outdoor field notes",
      tags: ["nature", "classification"],
    },
    {
      id: "demo-evidence-bridge",
      learnerId: "noah",
      title: "Building a bridge that holds the books",
      shortDescription: "Noah tested two paper bridge designs and recorded which structure held more books before bending.",
      learningArea: "STEM",
      date: "2026-03-17",
      reflection: "He changed the fold pattern after the first test and explained why the new shape was stronger.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Photo and observation",
      imageKey: "demo-building-bridge",
      imageAlt: "A fictional paper bridge model spanning two books with a small test weight",
      imagePlaceholder: "Future sample image: paper bridge building challenge",
      tags: ["design", "testing"],
    },
    {
      id: "demo-evidence-geography",
      learnerId: "noah",
      title: "Map notebook: rivers and regions",
      shortDescription: "Noah labelled a map with major rivers and regions, then added a short note about how water shapes settlement.",
      learningArea: "Geography",
      date: "2026-03-18",
      reflection: "He used the atlas to check one place name and corrected his own spelling before finishing the map.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Work sample",
      imageKey: "demo-geography-notebook",
      imageAlt: "A fictional geography notebook with a labelled river and regions map",
      imagePlaceholder: "Future sample image: geography notebook and map",
      tags: ["mapping", "research"],
    },
    {
      id: "demo-evidence-reflection",
      learnerId: "emma",
      title: "Garden project reflection",
      shortDescription: "Emma completed a short reflection about what changed in the garden project and what she wants to investigate next.",
      learningArea: "Project reflection",
      date: "2026-03-20",
      reflection: "Emma chose to keep measuring the sprouts and compare them after a sunny and cloudy week.",
      includeInPortfolio: true,
      includeInReport: true,
      evidenceType: "Project summary",
      imageKey: "demo-garden-reflection",
      imageAlt: "A fictional project reflection page beside a small garden journal",
      imagePlaceholder: "Future sample image: garden project reflection",
      tags: ["reflection", "next steps"],
    },
  ] satisfies DemoEvidenceRecord[],
} as const;

export type DemoEvidenceDataset = typeof demoEvidenceDataset;
