import type { MathematicsDetailedStrandGuide } from "@/lib/clean/pathways/mathematicsOperationsPrototype";

export const FRACTIONS_DECIMALS_PERCENTAGES_GUIDE: MathematicsDetailedStrandGuide = {
  key: "fractions-decimals-percentages",
  title: "Fractions, decimals, and percentages",
  subtitle:
    "Fractions, decimals, and percentages help learners describe parts, relationships, and proportional thinking with growing confidence. This strand builds naturally from number understanding and calculation, then opens the door to more flexible reasoning about quantity, comparison, scale, and value.",
  overview: [
    "Fractions, decimals, and percentages are different ways of describing quantity, especially when a whole is being split, compared, measured, or scaled.",
    "Early learning often begins with equal parts such as halves and quarters. Over time, learners begin to compare fractions, see equivalent relationships, and connect fractions to decimals and percentages.",
    "The goal is not memorising isolated conversions. It is helping learners recognise what these forms mean, when each form is useful, and how they connect in practical situations.",
  ],
  whyItMatters: [
    "working with money, discounts, and better-value shopping choices",
    "using cooking measurements, portions, and recipe scaling",
    "reading time, timetables, and parts of an hour",
    "sharing fairly and comparing equal or unequal portions",
    "interpreting statistics, tables, and simple data displays",
    "understanding sports percentages, game results, and success rates",
    "using maps, scales, and comparisons of size or distance",
    "budgeting, estimating, and interpreting information in everyday life",
  ],
  progressionStructure: [
    "recognising equal parts in practical and visual contexts",
    "working with halves, quarters, and other simple fractions",
    "using visual fraction models such as strips, shapes, and number lines",
    "noticing equivalent fractions and naming the same quantity in more than one way",
    "comparing and ordering fractions with growing confidence",
    "understanding decimals as number relationships rather than separate symbols",
    "using tenths and hundredths in measurement, money, and place value",
    "seeing percentages as out of 100 and connecting them to familiar comparisons",
    "connecting fractions, decimals, and percentages with increasing flexibility",
    "estimating sensibly and checking whether proportional comparisons make sense",
    "applying proportional thinking in practical situations such as value, chance, scale, and sharing",
  ],
  homeschoolExamples: [
    "cutting food into fair portions and discussing equal parts",
    "using recipe measurements such as half, quarter, or three-quarters",
    "working out shopping discounts, sale prices, or better buys",
    "sharing craft materials, snacks, or time fairly between siblings",
    "using probability or chance games with fraction or percentage language",
    "measuring lengths, liquids, or ingredients with decimal values",
    "comparing prices, pack sizes, or value using proportions",
    "tracking percentages in sports, games, or quiz scores",
    "using simple budgets and noticing what portion of the total is spent",
    "reading maps, scales, or model plans where quantities are compared proportionally",
  ],
  captureIdeas: [
    "a learner explanation of what a fraction, decimal, or percentage means in that task",
    "photos of visual models such as fraction strips, shaded diagrams, or number lines",
    "notes from practical measurement or cooking tasks",
    "budgeting or discount activities showing comparison reasoning",
    "annotated working that connects two or more forms of the same quantity",
    "short parent notes about verbal reasoning during a sharing, measuring, or shopping discussion",
    "problem-solving conversations about why one representation was more useful than another",
  ],
  portfolioIdeas: [
    "photos of visual fraction or decimal models that clearly show understanding",
    "learner reflections about how fractions, decimals, and percentages connect",
    "a real-world maths task such as a budget, recipe, or shopping comparison",
    "a percentage investigation or comparison completed over more than one day",
    "paired examples that show progress from concrete models to more flexible reasoning",
    "one strong comparison task where the learner explained why two values were equivalent or not",
  ],
  reportingExamples: [
    "The learner is developing stronger confidence with fractions and is increasingly able to explain equal parts, comparisons, and simple equivalence using practical examples.",
    "In measurement, cooking, and shopping contexts, the learner is beginning to connect fractions, decimals, and percentages more flexibly and with greater independence.",
    "Worked examples and discussion show growing confidence in using tenths and hundredths in familiar contexts such as money and measurement.",
    "The learner is becoming more thoughtful about comparing proportions and is starting to choose sensible representations when solving practical problems.",
    "Parent observations show increasing clarity in verbal reasoning when the learner explains discounts, portions, and percentage-based comparisons.",
  ],
  nextLearningConnections: [
    "ratio and proportional reasoning depends on seeing relationships between quantities clearly",
    "algebra grows when learners can generalise patterns and equivalent relationships",
    "measurement relies on decimals, fractions, scale, and unit comparison",
    "financial mathematics uses percentages, proportion, discounts, and value comparison",
    "probability uses fractions, decimals, and percentages to describe likelihood",
    "data and statistics often rely on percentages and proportional interpretation",
    "mathematical reasoning strengthens when learners can compare forms and justify which is most useful",
  ],
};
