import type { ActivityV5 } from "@/app/components/clean/activity-player-v5/types";

export function buildActivityPlayerV5Samples(): ActivityV5[] {
  return [
    {
      id: "gsr-step-4-move-route",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 4",
      mode: "practise",
      prompt: "Follow the route to the finish",
      instruction: "Start at A1. Move across the grid and finish at D3.",
      interactionType: "move_along_route",
      visualModel: "route_grid",
      objects: [],
      targets: [],
      correctState: { finalPosition: "D3" },
      feedback: {
        correct: "Yes. The route finishes at D3.",
        incorrect: "Trace the route again from the start and count each square.",
        hint: "Use the row and column labels to keep your place.",
      },
      supportHint: "Tap the square where the robot should finish.",
      worksheetReference: "GSR Step 4 route grid",
    },
    {
      id: "gsr-step-4-drag-arrangement",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 4",
      mode: "practise",
      prompt: "Copy the arrangement",
      instruction: "Place the triangle in the target that says roof.",
      interactionType: "drag_to_place",
      visualModel: "shape_board",
      objects: [{ id: "triangle", label: "Triangle", type: "triangle", draggable: true }],
      targets: [{ id: "roof", label: "roof", accepts: ["triangle"] }],
      correctState: { placements: { triangle: "roof" } },
      feedback: {
        correct: "Good. The triangle is placed where the roof belongs.",
        incorrect: "Look for the target that matches the triangle's role in the arrangement.",
      },
      supportHint: "Drag the triangle card, or tap it to place it.",
      worksheetReference: "GSR Step 4 arrangement copying",
    },
    {
      id: "gsr-step-6-plot-coordinates",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 6",
      mode: "practise",
      prompt: "Plot the coordinates",
      instruction: "Plot A1, B2, and C3 on the coordinate grid.",
      interactionType: "plot_coordinates",
      visualModel: "coordinate_grid",
      objects: [],
      targets: [],
      correctState: { plottedCoordinates: ["A1", "B2", "C3"] },
      feedback: {
        correct: "Correct. Each point is in the matching column and row.",
        incorrect: "Check the letter first, then the number.",
      },
      supportHint: "Column letters go across. Row numbers go down the side.",
      worksheetReference: "GSR Step 6 coordinate grid",
    },
    {
      id: "gsr-step-6-flip-reflection",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 6",
      mode: "practise",
      prompt: "Complete the reflection",
      instruction: "Use the mirror line to complete the reflected cells.",
      interactionType: "flip_reflection",
      visualModel: "reflection_grid",
      objects: [],
      targets: [],
      correctState: { reflectedCells: ["3-1", "3-2", "3-3"] },
      feedback: {
        correct: "Yes. The reflected cells match the same distance from the mirror line.",
        incorrect: "Each reflected cell should be the same distance from the mirror line as the original.",
      },
      supportHint: "Count away from the mirror line on both sides.",
      worksheetReference: "GSR Step 6 flip shape",
    },
    {
      id: "gsr-step-7-rotate-shape",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 7",
      mode: "practise",
      prompt: "Show a quarter turn clockwise",
      instruction: "Rotate the triangle to show a quarter turn clockwise.",
      interactionType: "rotate_shape",
      visualModel: "turn_board",
      objects: [],
      targets: [],
      correctState: { orientation: 90 },
      feedback: {
        correct: "Correct. A quarter turn clockwise is 90 degrees.",
        incorrect: "A quarter turn is one right-angle turn.",
      },
      supportHint: "Try the 90 degree option.",
      worksheetReference: "GSR Step 7 quarter turn",
    },
    {
      id: "gsr-step-7-click-angle",
      strand: "Geometry and Spatial Reasoning",
      step: "Step 7",
      mode: "practise",
      prompt: "Click the right angle",
      instruction: "Select the shape card that shows a right angle.",
      interactionType: "click_objects",
      visualModel: "shape_board",
      objects: [
        { id: "acute", label: "Acute angle", type: "triangle", selectable: true },
        { id: "right", label: "Right angle", type: "square", selectable: true },
        { id: "obtuse", label: "Obtuse angle", type: "rectangle", selectable: true },
      ],
      targets: [],
      correctState: { selectedObjectIds: ["right"] },
      feedback: {
        correct: "Yes. A right angle is a square corner.",
        incorrect: "Look for the angle that makes a square corner.",
      },
      supportHint: "A right angle is the corner of a square.",
      worksheetReference: "GSR Step 7 angle hunt",
    },
    {
      id: "operations-build-array",
      strand: "Operations and Calculation",
      step: "Array model sample",
      mode: "practise",
      prompt: "Build 3 rows of 4",
      instruction: "Use rows and columns to build the multiplication array.",
      interactionType: "build_array",
      visualModel: "array_board",
      objects: [],
      targets: [],
      correctState: { rows: 3, columns: 4 },
      feedback: {
        correct: "Correct. Three rows of four makes twelve.",
        incorrect: "Check the number of rows and the number in each row.",
      },
      supportHint: "Rows go across. Columns go down.",
    },
    {
      id: "apf-two-pan-balance",
      strand: "Algebra, Patterns and Functions",
      step: "Balanced equations sample",
      mode: "practise",
      prompt: "Show that both sides balance",
      instruction: "Inspect the two pans and choose whether the balance is equal, left heavier, or right heavier.",
      interactionType: "two_pan_balance",
      visualModel: "two_pan_balance_board",
      objects: [],
      targets: [],
      correctState: {
        leftItems: [
          { id: "left-5", label: "5", value: 5 },
          { id: "left-3", label: "3", value: 3 },
        ],
        rightItems: [{ id: "right-8", label: "8", value: 8 }],
        leftTotal: 8,
        rightTotal: 8,
        targetBalance: "balanced",
        equationText: "5 + 3 = 8",
        balanceMode: "compare",
      },
      feedback: {
        correct: "Correct. Both pans have the same total.",
        incorrect: "Add the tokens on each pan and compare the totals.",
      },
      supportHint: "A balanced equation has the same value on both sides.",
    },
    {
      id: "measurement-ruler",
      strand: "Measurement",
      step: "Ruler sample",
      mode: "practise",
      prompt: "Measure the pencil",
      instruction: "Move the slider until the ruler measurement is 6 units.",
      interactionType: "interactive_ruler",
      visualModel: "ruler_board",
      objects: [],
      targets: [],
      correctState: { measuredLength: 6, tolerance: 0 },
      feedback: {
        correct: "Correct. The pencil measures 6 units.",
        incorrect: "Line up the object with the ruler marks and try again.",
      },
    },
    {
      id: "measurement-clock",
      strand: "Measurement",
      step: "Clock sample",
      mode: "practise",
      prompt: "Set 9 o'clock",
      instruction: "Choose the clock time for school starts at 9 o'clock.",
      interactionType: "interactive_clock",
      visualModel: "clock_face",
      objects: [],
      targets: [],
      correctState: { hour: 9, minute: 0 },
      feedback: {
        correct: "Correct. The hour hand points to 9 and the minute hand points to 12.",
        incorrect: "For o'clock times, the minute hand points to 12.",
      },
    },
    {
      id: "fdp-fraction-bar",
      strand: "Fractions, Decimals and Percentages",
      step: "Fraction bar sample",
      mode: "practise",
      prompt: "Shade three quarters",
      instruction: "Click the bar part that shows 3 shaded parts out of 4.",
      interactionType: "interactive_fraction_bar",
      visualModel: "fraction_bar",
      objects: [],
      targets: [],
      correctState: { shadedParts: 3, denominator: 4 },
      feedback: {
        correct: "Correct. Three of the four equal parts are shaded.",
        incorrect: "Count how many equal parts are shaded.",
      },
    },
    {
      id: "fdp-fraction-comparison-board",
      strand: "Fractions, Decimals and Percentages",
      step: "Comparison and equivalent fractions sample",
      mode: "practise",
      prompt: "Compare the two fraction models",
      instruction: "Look at both same-sized fraction bars, then choose which side is larger or whether they are equal.",
      interactionType: "fraction_comparison",
      visualModel: "fraction_comparison_board",
      objects: [],
      targets: [],
      correctState: {
        leftFraction: { numerator: 2, denominator: 4 },
        rightFraction: { numerator: 1, denominator: 2 },
        leftLabel: "2/4",
        rightLabel: "1/2",
        comparisonAnswer: "equal",
      },
      feedback: {
        correct: "Correct. Two quarters and one half cover the same amount.",
        incorrect: "Compare the shaded length on both bars. The shaded parts line up.",
      },
      supportHint: "Both bars use the same whole, so compare the shaded length.",
      worksheetReference: "FDP comparison and equivalent-fraction visual model",
    },
    {
      id: "number-number-line",
      strand: "Number and Place Value",
      step: "Number line sample",
      mode: "practise",
      prompt: "Place 7 on the number line",
      instruction: "Tap the number line position for 7.",
      interactionType: "interactive_number_line",
      visualModel: "number_line",
      objects: [],
      targets: [],
      correctState: { numberLineValue: 7 },
      feedback: {
        correct: "Correct. The marker is on 7.",
        incorrect: "Count along the number line from 0.",
      },
    },
    {
      id: "number-place-value",
      strand: "Number and Place Value",
      step: "Place value sample",
      mode: "practise",
      prompt: "Build 34",
      instruction: "Build 34 using tens and ones.",
      interactionType: "build_place_value",
      visualModel: "place_value_blocks",
      objects: [],
      targets: [],
      correctState: { tens: 3, ones: 4 },
      feedback: {
        correct: "Correct. 34 is 3 tens and 4 ones.",
        incorrect: "Use three tens and four ones.",
      },
    },
    {
      id: "money-generic",
      strand: "Measurement",
      step: "Generic money sample",
      mode: "practise",
      prompt: "Make 7 with money tokens",
      instruction: "Select generic money tokens that total 7.",
      interactionType: "generic_money_model",
      visualModel: "money_board",
      objects: [
        { id: "coin-1", label: "1", value: 1 },
        { id: "coin-2", label: "2", value: 2 },
        { id: "note-5", label: "5", value: 5 },
        { id: "note-10", label: "10", value: 10 },
      ],
      targets: [],
      correctState: { moneyTotal: 7 },
      feedback: {
        correct: "Correct. The selected tokens total 7.",
        incorrect: "Try combining the 5 token and the 2 token.",
      },
    },
  ];
}
