import type { MetadataRoute } from "next";

const SITE_URL = "https://www.mylearna.com";

const PUBLIC_ALLOW_PATHS = [
  "/",
  "/demo",
  "/get-started",
  "/pricing",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/signup",
  "/login",
  "/faq",
  "/homeschool-answers",
  "/start-free",
  "/compare",
  "/homeschool-record-keeping",
  "/homeschool-learning-evidence",
  "/homeschool-portfolio",
  "/homeschool-reporting",
  "/homeschool-planning",
  "/homeschool-maths-worksheets",
];

const PRIVATE_DISALLOW_PATHS = [
  "/api",
  "/api/",
  "/auth",
  "/auth/",
  "/dashboard",
  "/exports",
  "/exports/",
  "/goals",
  "/goals/",
  "/onboarding",
  "/onboarding/",
  "/clean",
  "/clean/",
  "/clean-my-*",
  "/clean-my-assessments",
  "/clean-my-calendar",
  "/clean-my-capture",
  "/clean-my-curriculum",
  "/clean-my-day",
  "/clean-my-outputs",
  "/clean-my-pathways",
  "/clean-my-portfolio",
  "/clean-my-programs",
  "/clean-my-reports",
  "/my-*",
  "/my-assessments",
  "/my-calendar",
  "/my-capture",
  "/my-community",
  "/my-curriculum",
  "/my-data",
  "/my-day",
  "/my-learna",
  "/my-month",
  "/my-outputs",
  "/my-pathways",
  "/my-plan",
  "/my-portfolio",
  "/my-programs",
  "/my-progress",
  "/my-reports",
  "/my-review",
  "/my-settings",
  "/my-skills",
  "/home",
  "/home/",
  "/calendar",
  "/calendar/",
  "/capture",
  "/capture/",
  "/children",
  "/children/",
  "/curriculum",
  "/curriculum/",
  "/planner",
  "/planner/",
  "/portfolio",
  "/portfolio/",
  "/portfolio/share/",
  "/reports",
  "/reports/",
  "/authority",
  "/authority/",
  "/authority-au",
  "/authority-au/",
  "/authority-uk",
  "/authority-uk/",
  "/authority-us",
  "/authority-us/",
  "/family",
  "/family/",
  "/profile",
  "/profile/",
  "/settings",
  "/settings/",
  "/sign-out",
  "/reset-password",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: PUBLIC_ALLOW_PATHS,
        disallow: PRIVATE_DISALLOW_PATHS,
      },
      {
        userAgent: "OAI-SearchBot",
        allow: PUBLIC_ALLOW_PATHS,
        disallow: PRIVATE_DISALLOW_PATHS,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
