-- MyLearna Resource Factory v1 production foundation.
-- Applied to production as Supabase migration 20260926135755.

create table if not exists public.resource_factory_jobs (
  id uuid primary key default gen_random_uuid(),
  resource_id text not null unique,
  status text not null default 'planned',
  seed jsonb not null default '{}'::jsonb,
  spec jsonb,
  qa_report jsonb,
  marketplace_resource_id uuid references public.marketplace_resources(id) on delete set null,
  attempt_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint resource_factory_jobs_status_check
    check (
      status in (
        'planned',
        'generating',
        'generated',
        'qa',
        'qa_failed',
        'repairing',
        'rendering',
        'ready',
        'staged',
        'published',
        'promoted',
        'failed'
      )
    ),
  constraint resource_factory_jobs_attempt_count_check
    check (attempt_count >= 0)
);

create table if not exists public.resource_factory_artifacts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.resource_factory_jobs(id) on delete cascade,
  artifact_kind text not null,
  object_path text not null,
  mime_type text not null,
  byte_size bigint,
  created_at timestamptz not null default now(),
  constraint resource_factory_artifacts_kind_check
    check (artifact_kind in ('worksheet_pdf', 'answers_pdf', 'thumbnail', 'pinterest_image'))
);

create table if not exists public.resource_factory_events (
  id bigint generated by default as identity primary key,
  job_id uuid references public.resource_factory_jobs(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.marketplace_resource_metrics (
  id bigint generated by default as identity primary key,
  marketplace_resource_id uuid not null references public.marketplace_resources(id) on delete cascade,
  metric_date date not null,
  source text not null,
  impressions integer not null default 0,
  clicks integer not null default 0,
  saves integer not null default 0,
  downloads integer not null default 0,
  conversions integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketplace_resource_metrics_nonnegative_check
    check (
      impressions >= 0
      and clicks >= 0
      and saves >= 0
      and downloads >= 0
      and conversions >= 0
    ),
  constraint marketplace_resource_metrics_unique
    unique (marketplace_resource_id, metric_date, source)
);

create index if not exists resource_factory_jobs_status_created_idx
  on public.resource_factory_jobs(status, created_at);
create index if not exists resource_factory_artifacts_job_idx
  on public.resource_factory_artifacts(job_id);
create index if not exists resource_factory_events_job_created_idx
  on public.resource_factory_events(job_id, created_at desc);

alter table public.resource_factory_jobs enable row level security;
alter table public.resource_factory_artifacts enable row level security;
alter table public.resource_factory_events enable row level security;
alter table public.marketplace_resource_metrics enable row level security;

revoke all on table public.resource_factory_jobs from public, anon, authenticated;
revoke all on table public.resource_factory_artifacts from public, anon, authenticated;
revoke all on table public.resource_factory_events from public, anon, authenticated;
revoke all on table public.marketplace_resource_metrics from public, anon, authenticated;

grant select, insert, update, delete on table public.resource_factory_jobs to service_role;
grant select, insert, update, delete on table public.resource_factory_artifacts to service_role;
grant select, insert, update, delete on table public.resource_factory_events to service_role;
grant select, insert, update, delete on table public.marketplace_resource_metrics to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'resource-factory-public',
  'resource-factory-public',
  true,
  10485760,
  array['application/pdf']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
