"use client";

import Link from "next/link";
import { formatShopifyMoney } from "@/lib/shopify/money";
import { effectiveMarketplaceQuantityLimit } from "@/lib/shopify/inventory";
import { useMarketplaceCart } from "../MarketplaceCartProvider";

export default function CartView() {
  const { cart, loading, error, updateLine, removeLine, refresh } = useMarketplaceCart();
  if (loading) return <div className="marketplace-state" role="status">Loading your cart…</div>;
  if (error && !cart) return <div className="marketplace-state" role="alert"><strong>We could not load your cart.</strong><p>{error}</p><button className="marketplace-button secondary" type="button" onClick={() => void refresh()}>Try again</button></div>;
  if (!cart || !cart.lines.length) return <div className="marketplace-state"><strong>Your cart is empty.</strong><p>Explore the Marketplace and add a resource when you find one that fits.</p><Link className="marketplace-button" href="/marketplace/collections">Browse collections</Link></div>;
  return <div className="marketplace-cart"><div aria-live="polite">{error ? <p role="alert">{error}</p> : null}</div>{cart.lines.map((line) => { const maxQuantity = effectiveMarketplaceQuantityLimit(line.merchandise.quantityAvailable); return <div className="marketplace-cart-line" key={line.id}>{line.merchandise.product.featuredImage ? <img src={line.merchandise.product.featuredImage.url} alt={line.merchandise.product.featuredImage.altText || line.merchandise.product.title} /> : <span />}<div className="marketplace-cart-line-content"><Link className="marketplace-link" href={`/marketplace/products/${encodeURIComponent(line.merchandise.product.handle)}`}>{line.merchandise.product.title}</Link><p className="marketplace-cart-price">{formatShopifyMoney(line.cost.amountPerQuantity)}</p>{typeof line.merchandise.quantityAvailable === "number" ? <p className="marketplace-stock" role="status">{line.merchandise.quantityAvailable} available</p> : null}<label className="marketplace-label" htmlFor={`quantity-${line.id}`}>Quantity<input id={`quantity-${line.id}`} className="marketplace-input" type="number" min={1} max={maxQuantity} value={line.quantity} onChange={(event) => void updateLine(line.id, Math.min(maxQuantity, Math.max(1, Number(event.target.value) || 1)))} /></label></div><div className="marketplace-cart-line-actions"><button className="marketplace-button secondary" type="button" onClick={() => void removeLine(line.id)}>Remove</button></div></div>; })}<div className="marketplace-cart-summary"><div><div>Subtotal</div><strong>{formatShopifyMoney(cart.cost.subtotalAmount)}</strong></div>{cart.checkoutUrl ? <a className="marketplace-button" href={cart.checkoutUrl} target="_blank" rel="noreferrer noopener">Continue to secure checkout</a> : <span>Checkout is temporarily unavailable.</span>}</div></div>;
}
